### ISSUE TITLE
Better HTMLbars error for dumb HTML (attributes on closing tag)?

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#10117]
Upgrading an Ember app to use HTMLbars I got a cryptic error from some bad HTML:

```
<div class="span8">...</div class="span8">
```

It would be cool to get some kind of error saying something like: "Invalid markup on line 38: closing tags should not have attributes".

```
version: 0.1.5
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: client/templates/workshop/edit.hbs
Cannot call method 'push' of undefined
TypeError: Cannot call method 'push' of undefined
  at Object.Tokenizer.createAttribute (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3691:29)
  at Object.Tokenizer.states.beforeAttributeName (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:6802:18)
  at Object.Tokenizer.lex (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:6697:42)
  at Object.Tokenizer.tokenizePart (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:6562:24)
  at HTMLProcessor.nodeHandlers.ContentStatement (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3359:37)
  at HTMLProcessor.acceptNode (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3488:43)
  at HTMLProcessor.nodeHandlers.Program (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3298:16)
  at HTMLProcessor.acceptNode (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3488:43)
  at preprocess (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:3460:55)
  at compileSpec (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:678:17)
  at TemplateCompiler.__exports__.default [as precompile] (/Users/mitch/projects/tap/repo/client/bower_components/ember/ember-template-compiler.js:580:14)
  at TemplateCompiler.processString (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/index.js:58:38)
  at TemplateCompiler.Filter.processFile (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:136:31)
  at Promise.resolve.then.catch.err.file (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:82:21)
  at $$$internal$$tryCatch (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
  at /Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1096:13
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/mitch/projects/tap/repo/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by rwjblue** [comment]
Can you whip up a JSBin showing an example?

**Comment by mmun** [comment]
@mitchlloyd You should never be getting errors like this. It's a bug in the compiler. What template is causing this?

**Comment by oneeman** [comment]
You can get it by trying `<div></div foo=bar>` on htmlbars' http://localhost:4200/demos/compile-and-run.html .  I can take care of it unless someone else wants to.

**Comment by mmun** [comment]
@oneeman Please do.

**Comment by mitchlloyd** [comment]
Sorry, markdown fail in my original post: now you can see the template causing the error. @oneeman is correct.

**Comment by mitchlloyd** [comment]
Thanks for the quick fixes on these 2 issues everyone. Awesome work!

**Comment by oneeman** [comment]
:-)
