### ISSUE TITLE
Canary regression: ReferenceError: DEFAULT_FEATURES is not defined

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10224]
Discussed with @rwjblue
```
version: 0.1.7
DEFAULT_FEATURES is not defined
ReferenceError: DEFAULT_FEATURES is not defined
    at _Ember (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:203:24)
    at requireModule (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:54:65)
    at requireModule (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:50:24)
    at /Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:7049:1
    at Object.<anonymous> (/Users/jlegg/ember/boot/bower_components/ember/ember-template-compiler.js:7051:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
--> DEFAULT_FEATURES is supposed to be replaced by the config from Ember's default feature list

**Comment by cibernox** [comment]
I just hit that wall 10 minutes ago when updating ember-cli. 

Glad to see it wasn't me, because I had no clue why I was getting that error.

**Comment by rwjblue** [comment]
Ya, I broke the build. Will fix ASAP.
