### ISSUE TITLE
[DOC] Deprecated docs for ContainerView

### ISSUE THREAD

**Issue by Kuzirashi** [emberjs/ember.js#10299]
See this - http://emberjs.com/api/classes/Ember.ContainerView.html#toc_adding-and-removing-child-views - it shows setting `childViews` on Container which is deprecated. So, following code(taken from docs):
~~~~ JavaScript
aContainer = Ember.ContainerView.create({
  childViews: ['aView', 'bView', 'cView'],
  aView: Ember.View.create(),
  bView: Ember.View.create(),
  cView: Ember.View.create()
});
~~~~
Results in warning:
> DEPRECATION: Setting `childViews` on a Container is deprecated.
        at View.extend.init (http://builds.emberjs.com/tags/v1.9.1/ember.js:41164:15)
        at apply (http://builds.emberjs.com/tags/v1.9.1/ember.js:19661:32)
        at superWrapper [as init] (http://builds.emberjs.com/tags/v1.9.1/ember.js:19235:15)
        at apply (http://builds.emberjs.com/tags/v1.9.1/ember.js:19661:32)
        at new Class (http://builds.emberjs.com/tags/v1.9.1/ember.js:34513:9)
        at Function.ClassMixinProps.create (http://builds.emberjs.com/tags/v1.9.1/ember.js:34970:16)
        at suhegoqare.js:15:34
        at http://static.jsbin.com/js/prod/runner-3.25.6.min.js:1:13840
        at http://static.jsbin.com/js/prod/runner-3.25.6.min.js:1:10893

It seems like whole page about `Ember.ContainerView` needs refreshment. I don't feel competent to submit any PR here.

**Comment by xtian** [comment]
I believe this is a duplicate of #9833

**Comment by Kuzirashi** [comment]
Yes.  I'm closing this.
