### ISSUE TITLE
Build failed. File: ember-htmlbars/tests/helpers/view_test.jscs-test.js

### ISSUE THREAD

**Issue by Robdel12** [emberjs/ember.js#10378]
When trying to build the latest master I get a build error with jscs. Here's the stack trace:

```text
Unexpected token (3:1818)
SyntaxError: Unexpected token (3:1818)
  at raise (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
  at unexpected (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
  at expect (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1360:18)
  at parseExprList (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2443:9)
  at parseSubscripts (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2032:24)
  at parseExprSubscripts (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2012:12)
  at parseMaybeUnary (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
  at parseExprOps (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
  at parseMaybeConditional (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
  at parseMaybeAssign (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
  at parseExpression (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
  at parseStatement (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
  at parseBlock (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1826:18)
  at parseFunctionBody (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2378:19)
  at parseFunction (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2277:5)
  at parseExprAtom (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2141:14)
  at parseExprSubscripts (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
  at parseMaybeUnary (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
  at parseExprOps (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
  at parseMaybeConditional (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
  at parseMaybeAssign (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
  at parseExpression (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
  at parseExprList (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2448:22)
  at parseSubscripts (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2032:24)
  at parseExprSubscripts (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:2012:12)
  at parseMaybeUnary (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
  at parseExprOps (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
  at parseMaybeConditional (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
  at parseMaybeAssign (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
  at parseExpression (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
  at parseStatement (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
  at parseTopLevel (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:1526:18)
  at Object.exports.parse (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/node_modules/acorn/acorn.js:48:12)
  at getStandaloneModule (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/esperanto.js:531:14)
  at Object.toAmd (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/esperanto/esperanto.js:2452:9)
  at Mapper.fn (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/lib/utils/transpile-es6.js:16:22)
  at Mapper.processString (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/broccoli-stew/lib/map.js:77:15)
  at Mapper.Filter.processFile (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/broccoli-filter/index.js:136:31)
  at Promise.resolve.then.catch.err.file (/Users/robertdeluca/Projects/ember.js/node_modules/emberjs-build/node_modules/broccoli-filter/index.js:82:21)
  at $$$internal$$tryCatch (/Users/robertdeluca/Projects/ember.js/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/robertdeluca/Projects/ember.js/node_modules/rsvp/dist/rsvp.js:502:17)
  at /Users/robertdeluca/Projects/ember.js/node_modules/rsvp/dist/rsvp.js:1096:13
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/robertdeluca/Projects/ember.js/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:336:15)
```

@rwjblue has a [hunch it's related to](https://twitter.com/rwjblue/status/564116010245296128) a dependency update

**Comment by rwjblue** [comment]
JSCS enabled additional checks by default. This caused a few new style checking errors, which caused a bug to crop up in broccoli-jscs regarding escaping the error messages from JSCS.

Fix upstream: https://github.com/kellyselden/broccoli-jscs/pull/16
Temp fix in emberjs-build: https://github.com/emberjs/emberjs-build/pull/69

**Comment by rwjblue** [comment]
Thanks for filing this one, should be fixed now!

**Comment by Robdel12** [comment]
No problem! It builds now :grinning:
