### ISSUE TITLE
Acceptance tests cause error when destroying app in teardown function

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#10390]
Under Ember 1.11.0-beta.1, acceptance tests generates an error when calling `Ember.run(application, "destroy")` in the `teardown` method:

```
afterEach failed on visiting /: Cannot convert undefined or null to object
Source: 	
TypeError: Cannot convert undefined or null to object
    at Object.keys (native)
    at values (http://localhost:4200/assets/vendor.js:71458:24)
    at __exports__.default.Ember.Object.extend.willDestroy (http://localhost:4200/assets/vendor.js:71451:25)
    at superWrapper [as willDestroy] (http://localhost:4200/assets/vendor.js:30981:20)
    at Queue.invoke (http://localhost:4200/assets/vendor.js:14416:18)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:14481:13)
    at Object.DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:14286:19)
    at Object.Backburner.end (http://localhost:4200/assets/vendor.js:13711:27)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:13766:20)
    at Object.run [as default] (http://localhost:4200/assets/vendor.js:29316:27)
```

**Comment by rwjblue** [comment]
Please provide as simple of a reproduction as possible so we can try to look into this further.

**Comment by pgengler** [comment]
Simplest steps to reproduce from scratch:

* Generate a new project using ember-cli (0.1.12).
* Update Ember version to 1.11.0-beta.1:
```diff
diff --git a/bower.json b/bower.json
index 92d99a7..b7a5f97 100644
--- a/bower.json
+++ b/bower.json
@@ -1,9 +1,9 @@
 {
   "name": "test-app",
   "dependencies": {
-    "handlebars": "~1.3.0",
+    "handlebars": "~2.0.0",
     "jquery": "^1.11.1",
-    "ember": "1.8.1",
+    "ember": "1.11.0-beta.1",
     "ember-data": "1.0.0-beta.12",
     "ember-resolver": "~0.1.11",
     "loader.js": "ember-cli/loader.js#1.0.1",
```

```diff
diff --git a/package.json b/package.json
index ee87084..2c365f4 100644
--- a/package.json
+++ b/package.json
@@ -20,11 +20,11 @@
   "license": "MIT",
   "devDependencies": {
     "broccoli-asset-rev": "^2.0.0",
-    "broccoli-ember-hbs-template-compiler": "^1.6.1",
     "ember-cli": "0.1.12",
     "ember-cli-6to5": "^3.0.0",
     "ember-cli-content-security-policy": "0.3.0",
     "ember-cli-dependency-checker": "0.0.7",
+    "ember-cli-htmlbars": "^0.6.0",
     "ember-cli-ic-ajax": "0.1.1",
     "ember-cli-inject-live-reload": "^1.3.0",
     "ember-cli-qunit": "0.3.1",
```
* Create a simple acceptance test (modified slightly from the output of `ember generate acceptance-test dummy`):
```js
import Ember from 'ember';
import startApp from '../helpers/start-app';

var application;

module('Acceptance: Dummy', {
  setup: function() {
    application = startApp();
  },
  teardown: function() {
    Ember.run(application, 'destroy');
  }
});

test('visiting /', function() {
  visit('/');

  andThen(function() {
    equal(currentPath(), 'index');
  });
});
```

* Boot the application (`ember s`)
* Visit http://localhost:4200/tests to run the tests.

**Comment by abuiles** [comment]
@pgengler @rwjblue the problem here is not in Ember but coming from Ember-Data.. for now try ember-data: "canary" in your bower while a new version is released.

For more info check this out https://github.com/emberjs/data/pull/2691

**Comment by pgengler** [comment]
This is working now with ember data 1.0.0-beta.15. Thanks!
