### ISSUE TITLE
Text misinterpreted as `Unclosed element `

### ISSUE THREAD

**Issue by bndw** [emberjs/ember.js#10477]
Emberjs: v1.10.0
Ember-cli: v0.1.15

In the following template snippet, the `<--` arrow is misinterpreted as an HTML element.

```
{{#link-to "tornado"}}
    <p> <-- Go Back</p>
{{/link-to}}
```

```
bdw ~/projects/tornado/src/browser ember server
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: browser/pods/tornado/one/template.hbs
Unclosed element `go` (on line 6).
Error: Unclosed element `go` (on line 6).
    at HTMLProcessor.nodeHandlers.Program (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3385:17)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.BlockStatement (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3405:44)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.Program (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3375:16)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at preprocess (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3551:55)
    at compileSpec (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:741:17)
    at TemplateCompiler.__exports__.default [as precompile] (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:643:14)
    at TemplateCompiler.processString (/Users/bdw/projects/tornado/src/browser/node_modules/ember-cli-htmlbars/index.js:50:59)
```

**Comment by mixonic** [comment]
@bndw That HTML may work if entered into a browser, but it is not actually valid HTML5. Using the [HTML5 validator service](http://validator.w3.org/check) I see an error and suggestion that the `<` be encoded as a `&lt;`.

I agree we should have a better error message here. And this should likely be tracked at https://github.com/tildeio/htmlbars

**Comment by bndw** [comment]
@mixonic Good point; I'll move it over to htmlbars.
