### ISSUE TITLE
Assertion "Defining an injected controller property on a non-controller is not allowed." fails for ObjectControllers

### ISSUE THREAD

**Issue by Kerrick** [emberjs/ember.js#10610]
I seem to be unable to use `Ember.inject.controller()` on an `Ember.ObjectController`.

```js
App.IndexController = Ember.ObjectController.extend({
    application: Ember.inject.controller()
});
```

```
Error while processing route: index Assertion Failed: Defining an injected controller property on a non-controller is not allowed. Error: Assertion Failed: Defining an injected controller property on a non-controller is not allowed.
    at new Error (native)
    at Error.EmberError (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:12443:23)
    at Object.Ember.assert (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:3940:15)
    at controllerInjectionHelper (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:28098:13)
    at validatePropertyInjections (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:28798:13)
    at Function.injectedPropertyAssertion (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:34309:55)
    at factoryFor (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:1860:19)
    at Object.Container.lookupFactory (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:1422:16)
    at null.<anonymous> (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:22671:46)
    at Descriptor.ComputedPropertyPrototype.get (http://builds.emberjs.com/tags/v1.10.0/ember.debug.js:10825:25)
```

http://emberjs.jsbin.com/resenaraha/1/edit?html,css,js,output

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/10612 should address this
