### ISSUE TITLE
No method `getTokenPosByRangeStart` causing build to fail

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#10743]
Trying to get a local build up and running, but seems to be failing. I've seen the note to not use Node v0.12 yet, so I'm running v0.10.38. I get the below error:

```bash
Engelbert:ember.js trentmwillis$ npm test

> ember@1.12.0-beta.1 pretest /Users/trentmwillis/workspace/ember.js
> ember build

Future versions of Ember CLI will not support v0.10.38. Please update to Node 0.12 or io.js.
version: 0.2.1
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Build failed.
File: container/container.js
Object #<Object> has no method 'getTokenPosByRangeStart'
TypeError: Object #<Object> has no method 'getTokenPosByRangeStart'
    at /Users/trentmwillis/workspace/ember.js/lib/jscs-rules/require-spaces-after-closing-parenthesis-in-function-declaration.js:37:35
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-jscs/node_modules/jscs/lib/js-file.js:406:42)
    at Object.module.exports.check (/Users/trentmwillis/workspace/ember.js/lib/jscs-rules/require-spaces-after-closing-parenthesis-in-function-declaration.js:30:10)
    at null.<anonymous> (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:133:18)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:131:31)
    at StringChecker.checkString (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:111:14)
    at JSCSFilter.processString (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-jscs/index.js:58:31)
    at Filter.processFile (/Users/trentmwillis/workspace/ember.js/node_modules/emberjs-build/node_modules/broccoli-filter/index.js:139:31)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by rwjblue** [comment]
Was removed in: https://github.com/jscs-dev/node-jscs/pull/1076

**Comment by rwjblue** [comment]
It is used in https://github.com/emberjs/ember.js/blob/master/lib/jscs-rules/require-spaces-after-closing-parenthesis-in-function-declaration.js
