### ISSUE TITLE
Object doesn't support property or method 'setAttribute' IE 11

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/ember.js#10786]
We are seeing this error on our site when using Internet Explorer 11, the error is. 

```
TypeError: Object doesn't support property or method 'setAttribute'
   at prototype.setAttribute (http://localapp:5000/assets/vendor.js:13215:7)
   at actionHelper (http://localapp:5000/assets/vendor.js:29183:5)
   at element (http://localapp:5000/assets/vendor.js:17844:7)
   at render (http://localapp:5000/assets/survey.js:10657:9)
   at renderHTMLBarsTemplate (http://localapp:5000/assets/vendor.js:18388:5)
   at renderView (http://localapp:5000/assets/vendor.js:18355:7)
   at renderView (http://localapp:5000/assets/vendor.js:47271:5)
   at render (http://localapp:5000/assets/vendor.js:47292:7)
   at EmberRenderer_createElement (http://localapp:5000/assets/vendor.js:49416:9)
   at Renderer_renderTree (http://localapp:5000/assets/vendor.js:18978:7)
```

I've been trying to recreate it on a jsbin all morning, but haven't been able to. I've removed all the code in our app except for this on the template, which causes the error. 

```
<a href="javascript:" {{action 'next'}}>Continue</a>.
```

A blank page with only that template code and I get the error when I go to the next route and then go back to the previous route, it causes the error above to show up in IE 11. 

Changing a href to a div or something else still causes it. 

I can message a link to our site if you would like to replicate it, as I said I I tried to replicate it on a jsBin, but wasn't able to. We were running 11 beta-5 on production and didn't see this error, so I believe it showed up between beta-5 and the release.

Update: 

Looking a little more, it might be related to setAttribute method on a text node, vs the actual link with the action.

**Comment by aaronbhansen** [comment]
I've done more research into this, and as far as I can tell, in the setup we have, using [Right Single Quotation Mark U+2019](http://unicode-table.com/en/2019) in our template is breaking Internet Explorer 11. I change it to a [Apostrophe U+0027](http://unicode-table.com/en/0027) and the page no longer has issues rendering. 

I've tried replicating this with jsbins, but template compilation is different, or there is something else different on our setup. If you want more specifics on our setup and package versions I can give you that, otherwise I can close it if you don't want to look into it further.
