### ISSUE TITLE
Error while processing route: courses.index Cannot read property 'match' of undefined TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by justqyx** [emberjs/ember.js#10854]
I got this error when I try to get `Course` records in `app/routes/courses/index.js`.

```
Preparing to transition from '' to 'courses.index'
ember.debug.js:5178WARNING: Encountered "0" in payload, but no model was found for model name "0" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("0"))
ember.debug.js:5178WARNING: Encountered "1" in payload, but no model was found for model name "1" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("1"))
ember.debug.js:5178WARNING: Encountered "2" in payload, but no model was found for model name "2" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("2"))
ember.debug.js:5178WARNING: Encountered "3" in payload, but no model was found for model name "3" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("3"))
ember.debug.js:5178WARNING: Encountered "4" in payload, but no model was found for model name "4" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("4"))
ember.debug.js:5178WARNING: Encountered "5" in payload, but no model was found for model name "5" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("5"))
ember.debug.js:5178WARNING: Encountered "6" in payload, but no model was found for model name "6" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("6"))
ember.debug.js:5178WARNING: Encountered "7" in payload, but no model was found for model name "7" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("7"))
ember.debug.js:5178WARNING: Encountered "8" in payload, but no model was found for model name "8" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("8"))
ember.debug.js:5178WARNING: Encountered "9" in payload, but no model was found for model name "9" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("9"))
ember.debug.js:5178WARNING: Encountered "_super" in payload, but no model was found for model name "super" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("_super"))
ember.debug.js:5178WARNING: Encountered "nextObject" in payload, but no model was found for model name "nextObject" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("nextObject"))
ember.debug.js:5178WARNING: Encountered "firstObject" in payload, but no model was found for model name "firstObject" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("firstObject"))
ember.debug.js:5178WARNING: Encountered "lastObject" in payload, but no model was found for model name "lastObject" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("lastObject"))
ember.debug.js:5178WARNING: Encountered "contains" in payload, but no model was found for model name "contain" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("contains"))
ember.debug.js:5178WARNING: Encountered "getEach" in payload, but no model was found for model name "getEach" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("getEach"))
ember.debug.js:5178WARNING: Encountered "setEach" in payload, but no model was found for model name "setEach" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("setEach"))
ember.debug.js:5178WARNING: Encountered "mapBy" in payload, but no model was found for model name "mapBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("mapBy"))
ember.debug.js:5178WARNING: Encountered "mapProperty" in payload, but no model was found for model name "mapProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("mapProperty"))
ember.debug.js:5178WARNING: Encountered "reject" in payload, but no model was found for model name "reject" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("reject"))
ember.debug.js:5178WARNING: Encountered "filterBy" in payload, but no model was found for model name "filterBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("filterBy"))
ember.debug.js:5178WARNING: Encountered "filterProperty" in payload, but no model was found for model name "filterProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("filterProperty"))
ember.debug.js:5178WARNING: Encountered "rejectBy" in payload, but no model was found for model name "rejectBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("rejectBy"))
ember.debug.js:5178WARNING: Encountered "rejectProperty" in payload, but no model was found for model name "rejectProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("rejectProperty"))
ember.debug.js:5178WARNING: Encountered "find" in payload, but no model was found for model name "find" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("find"))
ember.debug.js:5178WARNING: Encountered "findBy" in payload, but no model was found for model name "findBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("findBy"))
ember.debug.js:5178WARNING: Encountered "findProperty" in payload, but no model was found for model name "findProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("findProperty"))
ember.debug.js:5178WARNING: Encountered "everyBy" in payload, but no model was found for model name "everyBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("everyBy"))
ember.debug.js:5178WARNING: Encountered "everyProperty" in payload, but no model was found for model name "everyProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("everyProperty"))
ember.debug.js:5178WARNING: Encountered "isEvery" in payload, but no model was found for model name "isEvery" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("isEvery"))
ember.debug.js:5178WARNING: Encountered "any" in payload, but no model was found for model name "any" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("any"))
ember.debug.js:5178WARNING: Encountered "isAny" in payload, but no model was found for model name "isAny" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("isAny"))
ember.debug.js:5178WARNING: Encountered "anyBy" in payload, but no model was found for model name "anyBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("anyBy"))
ember.debug.js:5178WARNING: Encountered "someProperty" in payload, but no model was found for model name "someProperty" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("someProperty"))
ember.debug.js:5178WARNING: Encountered "invoke" in payload, but no model was found for model name "invoke" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("invoke"))
ember.debug.js:5178WARNING: Encountered "toArray" in payload, but no model was found for model name "toArray" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("toArray"))
ember.debug.js:5178WARNING: Encountered "compact" in payload, but no model was found for model name "compact" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("compact"))
ember.debug.js:5178WARNING: Encountered "without" in payload, but no model was found for model name "without" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("without"))
ember.debug.js:5178WARNING: Encountered "uniq" in payload, but no model was found for model name "uniq" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("uniq"))
ember.debug.js:5178WARNING: Encountered "[]" in payload, but no model was found for model name "[]" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("[]"))
ember.debug.js:5178WARNING: Encountered "addEnumerableObserver" in payload, but no model was found for model name "addEnumerableObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("addEnumerableObserver"))
ember.debug.js:5178WARNING: Encountered "removeEnumerableObserver" in payload, but no model was found for model name "removeEnumerableObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("removeEnumerableObserver"))
ember.debug.js:5178WARNING: Encountered "hasEnumerableObservers" in payload, but no model was found for model name "hasEnumerableObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("hasEnumerableObservers"))
ember.debug.js:5178WARNING: Encountered "enumerableContentWillChange" in payload, but no model was found for model name "enumerableContentWillChange" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("enumerableContentWillChange"))
ember.debug.js:5178WARNING: Encountered "enumerableContentDidChange" in payload, but no model was found for model name "enumerableContentDidChange" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("enumerableContentDidChange"))
ember.debug.js:5178WARNING: Encountered "sortBy" in payload, but no model was found for model name "sortBy" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("sortBy"))
ember.debug.js:5178WARNING: Encountered "objectAt" in payload, but no model was found for model name "objectAt" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("objectAt"))
ember.debug.js:5178WARNING: Encountered "objectsAt" in payload, but no model was found for model name "objectsAt" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("objectsAt"))
ember.debug.js:5178WARNING: Encountered "addArrayObserver" in payload, but no model was found for model name "addArrayObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("addArrayObserver"))
ember.debug.js:5178WARNING: Encountered "removeArrayObserver" in payload, but no model was found for model name "removeArrayObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("removeArrayObserver"))
ember.debug.js:5178WARNING: Encountered "hasArrayObservers" in payload, but no model was found for model name "hasArrayObserver" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("hasArrayObservers"))
ember.debug.js:5178WARNING: Encountered "arrayContentWillChange" in payload, but no model was found for model name "arrayContentWillChange" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("arrayContentWillChange"))
ember.debug.js:5178WARNING: Encountered "arrayContentDidChange" in payload, but no model was found for model name "arrayContentDidChange" (resolved model name using neolion-desktop@serializer:-rest:.typeForRoot("arrayContentDidChange"))
Error while processing route: courses.index Cannot read property 'match' of undefined TypeError: Cannot read property 'match' of undefined
    at Ember.DefaultResolver.extend.podBasedComponentsInSubdir (http://localhost:4200/assets/vendor.js:60138:76)
    at http://localhost:4200/assets/vendor.js:60190:34
    at Array.exports.default.mixin.Mixin.create.find (http://localhost:4200/assets/vendor.js:39572:30)
    at Ember.DefaultResolver.extend.findModuleName (http://localhost:4200/assets/vendor.js:60188:44)
    at resolveOther (http://localhost:4200/assets/vendor.js:60051:37)
    at superWrapper (http://localhost:4200/assets/vendor.js:28141:20)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15454:35)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:15217:23)
    at resolve (http://localhost:4200/assets/vendor.js:12792:29)
    at Object.Registry.resolve (http://localhost:4200/assets/vendor.js:12336:21)
```

ENV

```
DEBUG: -------------------------------
ember.debug.js:5197DEBUG: Ember             : 1.11.1
ember.debug.js:5197DEBUG: Ember Data        : 1.0.0-beta.16.1
ember.debug.js:5197DEBUG: jQuery            : 1.11.2
ember.debug.js:5197DEBUG: Ember Simple Auth : 0.7.3
ember.debug.js:5197DEBUG: -------------------------------
VM41602:66 Ember Inspector Active
```

the router

```js
// app/router.js
import Ember from 'ember';
import config from './config/environment';

var Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('login');

  this.resource('courses', function() {
    this.route('show', { path: '/:course_id' });
  });

});

export default Router;
```

the adapter

```js
// app/adapters/application.js
import DS from 'ember-data';
import ENV from '../config/environment';

var conf = {
  namespace: 'api'
};

if (ENV.online) {
  conf.host = ENV.API_HOST;
}

export default DS.RESTAdapter.extend(conf);
```

the mdoels

```js
// app/models/course.js
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  desc: DS.attr('string'),
  image_url: DS.attr('string'),
  rating: DS.attr('number'),
  price: DS.attr('number'),
  learned_count: DS.attr('number'),
  purchased: DS.attr('boolean'),
  teacher: DS.belongsTo('teacher')
});
```

```js
// app/models/teacher.js
import DS from 'ember-data';

export default DS.Model.extend({
  profile: DS.attr('string'),
  user: DS.belongsTo('user')
});
```

```js
// app/models/user.js
import DS from 'ember-data';

export default DS.Model.extend({
  avatar_url: DS.attr('string'),
  birthday: DS.attr('date'),
  education: DS.attr('string'),
  gender: DS.attr('string'),
  industry: DS.attr('string'),
  is_teacher: DS.attr('boolean'),
  job: DS.attr('string'),
  nickname: DS.attr('string'),
  work_experience: DS.attr('string')
});
```

The ajax request is successful with repsonse data like: 

```
[
    { id: 1,
      title: "TITLE 1",
      teacher: {
          id: 1, ...
          user: {  id: 1, .... }
      }
    },
    { id: 1,
      title: "TITLE 1",
      teacher: {
          id: 1, ...
          user: {  id: 1, .... }
      }
    },
   ...
]
```

It's not RESTFul, so I overwrite the `extractArray` method

```js
// app/serializers/courses/index.js
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
  // Transformation
  //
  // eg：
  //
  // {
  //    courses: [
  //      { id: 1, title: "Title1", teacher: 1 },
  //      { id: 2, title: "Title1", teacher: 2 },
  //    ],
  //    teachers: [
  //      { id: 1, name: "T1", user: 1 },
  //      { id: 2, name: "T2", user: 2 },
  //    ],
  //    users: [
  //      { id: 1, nickname: "robot1" },
  //      { id: 2, nickname: "robot2" }
  //    ]
  // }
  extractArray: function(store, type, payload) {
    console.info("===== Extract Array =====");

    var courses   = [];
    var teachers  = [];
    var users     = [];

    var teacherIdsCache = [];
    var userIdsCache = [];

    payload.forEach(function(course) {
      var teacher = course.teacher;
      var user    = teacher.user;

      delete course.teacher;
      delete teacher.user;

      course.teacher = teacher.id;
      teacher.user   = user.id;

      courses.push(course);

      if (!(teacherIdsCache.contains(teacher.id))) {
        teachers.push(teacher);
        teacherIdsCache.push(teacher.id);
      }

      if (!(userIdsCache.contains(user.id))) {
        userIdsCache.push(user.id);
        users.push(user);
      }
    });

    payload = { courses: courses, teachers: teachers, users: users };

    return this._super(store, type, payload);
  }
});
```

I don't know where is wrong, please help.

**Comment by justqyx** [comment]
This is an app build by Ember CLI，I found I just put the `serializer` in the wrong fold，should be `app/serializers/course.js` instead of `app/serializers/courses/index.js`. Oh my god!

**Comment by xtian** [comment]
@justqyx Glad you caught the issue. You're able to close the issue with the button next to **Comment**

I'm not sure I understand your question about `RESTSerializer`, though.

**Comment by justqyx** [comment]
@xitian It can has a custom serializer for Model but not for Route. I'm just confused.
