### ISSUE TITLE
1.11.3 Error while processing route: form controller._updateCacheParams is not a function

### ISSUE THREAD

**Issue by tpanagos** [emberjs/ember.js#10956]
Upgraded from 1.9.x to 1.11.3 and am getting a consistent error on previously functioning code.

Error is:
Error while processing route: form controller._updateCacheParams is not a function TypeError: controller._updateCacheParams is not a function
    at EmberObject.default.extend.setup (http://localhost:9000/assets/javascripts/ember.debug.js:71815:24)
    at callHook (http://localhost:9000/assets/javascripts/ember.debug.js:96049:44)
    at handlerEnteredOrUpdated (http://localhost:9000/assets/javascripts/ember.debug.js:94798:11)
    at setupContexts (http://localhost:9000/assets/javascripts/ember.debug.js:94765:15)
    at finalizeTransition (http://localhost:9000/assets/javascripts/ember.debug.js:94939:13)
    at http://localhost:9000/assets/javascripts/ember.debug.js:94374:20
    at tryCatch (http://localhost:9000/assets/javascripts/ember.debug.js:96386:20)
    at invokeCallback (http://localhost:9000/assets/javascripts/ember.debug.js:96398:21)
    at publish (http://localhost:9000/assets/javascripts/ember.debug.js:96369:15)
    at http://localhost:9000/assets/javascripts/ember.debug.js:76702:9

[JsBin] (http://jsbin.com/mezubu/1/)

**Comment by tpanagos** [comment]
Have tried multiple names for the route/controller/form just to clear the potential that "form" is reserved. Name does not affect the outcome.

**Comment by tpanagos** [comment]
Found my error. Intending to refactoring ObjectController to Controller, I removed the Controller and left the Object which, of course, is NOT a Controller. 

        window.App.TimController = Ember.Object.extend({
            facts: {foo:"bar"}
        });

        window.App.TimController = Ember.Controller.extend({
            facts: {foo:"bar"}
        });
