### ISSUE TITLE
TypeError: Cannot set property readonly of [object Object] which has only a getter

### ISSUE THREAD

**Issue by miguelmota** [emberjs/ember.js#11125]
```
DEBUG: -------------------------------                                                      
DEBUG: Ember      : 1.12.0-beta.3                                                           
DEBUG: Ember Data : 1.0.0-beta.17                                                           
DEBUG: jQuery     : 2.1.4                                                                   
DEBUG: -------------------------------                                                      
[ ] -view-registry:main ........................................ acorns/main/-view-registry 
//  ...
TypeError: Cannot set property readonly of [object Object] which has only a getter
 at DOMHelper.prototype.setPropertyStrict in http://localhost:4200/assets/vendor.js:14965:21
 at AttrMorph.updateProperty [as _update] in http://localhost:4200/assets/vendor.js:54336:22
 at AttrMorph.setContent in http://localhost:4200/assets/vendor.js:54379:14
 at AttrNode.render in http://localhost:4200/assets/vendor.js:47169:19
 at EmberRenderer_createElement [as createElement] in http://localhost:4200/assets/vendor.js:49860:12
 at EmberRenderer.Renderer_renderTree [as renderTree] in http://localhost:4200/assets/vendor.js:21551:22
 at EmberRenderer.scheduledRenderTree in http://localhost:4200/assets/vendor.js:21627:12
 at Queue.invoke in http://localhost:4200/assets/vendor.js:13289:18
 at Object.Queue.flush in http://localhost:4200/assets/vendor.js:13354:13
 at Object.DeferredActionQueues.flush in http://localhost:4200/assets/vendor.js:13159:19
```

`http://localhost:4200/assets/vendor.js:14965:21`

```
    prototype.setPropertyStrict = function(element, name, value) {
      element[name] = value; // <--
    };
```

**Comment by rwjblue** [comment]
The error is coming from an attempt to set the `readonly` property on an element.  What element?  What browser?

Can you please provide a JSBin reproduction?

**Comment by miguelmota** [comment]
@rwjblue yes that is correct

```
{{input readonly="readonly" disabled="disabled" value=value}}
```

throws the error. My current workaround is

```
<input disabled="disabled" readonly="readonly" {{bind-attr value=value}}>
```

It's happening on the [zombie](http://zombie.js.org/) headless simulated browser.

That's all you need to reproduce the error above.

**Comment by rwjblue** [comment]
We have changed the way we deal with props/attributes and this may be fixed, but I don't have `zombie` setup locally to test.

**Comment by pixelhandler** [comment]
@miguelmota is this still an issue?

**Comment by miguelmota** [comment]
@pixelhandler haven't retested but you can close this issue since nobody else has reported it.
