### ISSUE TITLE
Canary - Poor bind-attr deprecation warning messages

### ISSUE THREAD

**Issue by danmcclain** [emberjs/ember.js#11133]
The bind-attr deprecation warning error message does not yield any context where the issue is coming from:

```
DEPRECATION: The `bind-attr` helper is deprecated in favor of HTMLBars-style bound attributes
        at isBindAttrModifier (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:9626:24)
        at /Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:9521:15
        at Walker.visit (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:15411:7)
        at visitors.Program (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:15421:16)
        at Walker.children (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:15444:7)
        at Walker.visit (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:15412:12)
        at TransformBindAttrToAttributes_transform [as transform] (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-
template-compiler.js:9516:12)
        at Object.preprocess (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:15011:27)
        at compileSpec (/Users/dan/Projects/dockyard/client_work/web-client/bower_components/ember/ember-template-compiler.js:10535:22)
```

/cc @rwjblue

**Comment by rwjblue** [comment]
:+1: - We need to add the filename + line/column info to this deprecation.

**Comment by rwjblue** [comment]
I'll tackle shortly....
