### ISSUE TITLE
Poor deprecation notice for using `classBinding` in a template.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11263]
```
DEPRECATION: You're using legacy class binding syntax: classBinding=":input type socialMediaValidClass" @ 4:60 in (inline). Please replace with class=""
        at /Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:10393:26
        at each (/Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:10460:7)
        at /Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:10378:7
        at Walker.visit (/Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:15645:7)
        at visitors.ElementNode (/Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:15661:16)
        at Walker.children (/Users/rwjblue/src/ember-land/ember-canary/dist/ember-template-compiler.js:15678:7)
```

Needs to include moduleName and line number if possible, along with the corrected syntax.

Demo JSBin: http://emberjs.jsbin.com/rwjblue/542/edit?html,js

**Comment by ivpusic** [comment]
How I can get rid of ``classBinding`` deprecation in this case?

```{{input classBinding=":validate errors:invalid"}}```
