### ISSUE TITLE
ember 1.13.1 - infinite loop deprecation warning triggered

### ISSUE THREAD

**Issue by dagda1** [emberjs/ember.js#11718]
I am trying to upgrade [this](https://github.com/dagda1/emberx-autosuggest) addon.

I am trying to run [this](https://github.com/dagda1/emberx-autosuggest/blob/upgrade/tests/acceptance/customisations-test.js) test fixture on the upgrade branch.

I am testing a component in its block form like this:
```
  {{#x-autosuggest source=model destination=tags minChars=0 as |selection|}}
    <img src="img/small_avatar.png" alt="{{selection.name}} class="avatar"/>
  {{/x-autosuggest}}
```

If the component is in its block form then ember goes into an infinite loop spitting out the following deprecation warning:

```
DEPRECATION: You modified result twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:7357/assets/vendor.js:58999:38)
        at http://localhost:7357/assets/vendor.js:21828:32
        at Object.Stream.notifySubscribers (http://localhost:7357/assets/vendor.js:31127:11)
        at Object.Stream.notifyExcept (http://localhost:7357/assets/vendor.js:31067:14)
        at Object.Stream.notify (http://localhost:7357/assets/vendor.js:31061:12)
        at Object.bindLocal (http://localhost:7357/assets/vendor.js:18015:16)
        at Object.updateLocal (http://localhost:7357/assets/vendor.js:60052:15)
        at RenderResult.updateLocals (http://localhost:7357/assets/vendor.js:61069:22)
        at RenderResult.revalidateWith (http://localhost:7357/assets/vendor.js:60991:12)
        at Object.block [as default] (http://localhost:7357/assets/vendor.js:61559:31)
```

It does not matter if there is anything within the block.

If I run the test with the component in non-block form then the test executes.

Why would this cause an infinite loop?

**Comment by dagda1** [comment]
The warning message is absolutely correct because I have this test-helper:

```
function fillInWithInputEvents(app, selector, contextOrText, textOrEvents, events) {
  var $el, context, text;

  if (typeof events === 'undefined') {
    context = null;
    text = contextOrText;
    events = textOrEvents;
  } else {
    context = contextOrText;
    text = textOrEvents;
  }

  if (typeof events === 'string') {
    events = [events];
  }

  $el = app.testHelpers.findWithAssert(selector, context);

  $el.val('');

  focus($el);

  function fillInWithInputEvent(character) {
    var val = $el.val();
    var charCode = character.charCodeAt(0);

    val += character;

    run(function() {
      $el.val(val).change();
    });

    for (var i = 0, l = events.length; i < l; i++) {
      run($el, "trigger", events[i], { keyCode: charCode, which: charCode });
    }
  }

  for (var i = 0, l = text.length; i < l; i++) {
    fillInWithInputEvent(text[i]);
  }

  return app.testHelpers.wait();
}
```
That I call like this to simulate input events such as ```keyDown``` and  ```input```.

```
.fillInWithInputEvents('input.autosuggest', 'Paul',['keydown', 'input']  ).then(function(){
```

So I am manually triggering an event more than once.  

The fact that it goes into an infinite loop is still a bug though.

**Comment by krisselden** [comment]
@wycats should we keep a count of how many top level revalidates per run loop and error when it hits a certain count?

**Comment by Serabe** [comment]
@krisselden is this still an issue now Ember 1.13 is long gone?

**Comment by krisselden** [comment]
@Serabe the issue itself was an infinite sync loop in one run loop,  my suggestion of keeping a count of renders for one run loop I think still applicable but we can close this issue
