### ISSUE TITLE
Build error when editing JS files

### ISSUE THREAD

**Issue by RaySinlao** [emberjs/ember.js#12530]
While developing locally I get a build error every time I save a JS file. 

Restarting the server fixes the error until I save again. 

```
ENOENT: no such file or directory, unlink '/Users/ray/Desktop/new-app/tmp/babel-output_path-0Y1g5bc3.tmp/new-app/models/friend.js'
Error: ENOENT: no such file or directory, unlink '/Users/ray/Desktop/new-app/tmp/babel-output_path-0Y1g5bc3.tmp/new-app/models/friend.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:937:18)
    at Babel.<anonymous> (/Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:85:12)
    at /Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/ray/Desktop/new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by stefanpenner** [comment]
can you please share which versions you are using?

**Comment by RaySinlao** [comment]
version: 1.13.8
node: 4.2.1
npm: 2.13.4
os: darwin x64

**Comment by stefanpenner** [comment]
what is the result of:

```
npm ls broccoli-persistent-filter
```

**Comment by RaySinlao** [comment]
├─┬ ember-cli-babel@5.1.5
│ └─┬ broccoli-babel-transpiler@5.4.5
│   └── broccoli-persistent-filter@1.1.2
├─┬ ember-cli-qunit@1.0.3
│ └─┬ broccoli-jshint@1.1.0
│   └── broccoli-persistent-filter@1.1.2
└─┬ emberfire@1.6.0
  └─┬ ember-cli-babel@5.0.0
    └─┬ broccoli-babel-transpiler@5.4.5
      └── broccoli-persistent-filter@1.1.2

**Comment by stefanpenner** [comment]
broccoli-persistent-filter 1.1.3 should likely fix this issue, please:

```
npm cache clear
rm -rf node_modules
npm i
```

**Comment by RaySinlao** [comment]
That fixed it!

**Comment by stefanpenner** [comment]
:)
