### ISSUE TITLE
Attempting to install latest Ember as a node package is failling

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#12573]
Only the following versions are available from npm:
```shell
["0.9.7-1","0.9.8","0.9.8-1","1.0.0-pre","1.0.0-pre.m1","1.0.0-pre.m2","1.0.0-pre.2"]
```

**Comment by olivierlesnicki** [comment]
None of the available versions are actually working.

index.js
```
require('ember');
```

Results in:
```shell
ReferenceError: window is not defined
    at /Users/pro/Workbench/Centrica/sandbox/ember-node/node_modules/ember/rsvp.js:215:5
    at Object.<anonymous> (/Users/pro/Workbench/Centrica/sandbox/ember-node/node_modules/ember/rsvp.js:217:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pro/Workbench/Centrica/sandbox/ember-node/node_modules/ember/runtime.js:6:1)
    at Module._compile (module.js:434:26)
```

with version `1.0.0-pre.2`

and

```
SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pro/Workbench/Centrica/sandbox/ember-node/node_modules/ember/node_modules/window/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

with version `0.9.7-1`

**Comment by stefanpenner** [comment]
`ember` is not an official package for us. Ember has not historically shipped with `npm` but that should be changing this month.

Sorry for the confusion.

**Comment by olivierlesnicki** [comment]
@stefanpenner is there a PR or RFC I can follow for this?

**Comment by stefanpenner** [comment]
- https://github.com/emberjs/ember.js/pull/12412
- https://github.com/emberjs/data/pull/3813

It is likely we will reserve the ember package for something else

- [ ] release ember package sentinel that throws with helpful message if user tries to use

cc @ef4 i think you mentioned this, do you by anychance of the required cycles ?

**Comment by olivierlesnicki** [comment]
@stefanpenner thanks

**Comment by locks** [comment]
Please track this at https://github.com/emberjs/ember.js/pull/13022.
