### ISSUE TITLE
Build error in ember-template-compiler on self closing html tag 

### ISSUE THREAD

**Issue by mozeryansky** [emberjs/ember.js#12769]
The current example in the guides has this example:
`<input type="text" value={{favoriteBand}} onblur={{action "bandDidChange"}}/>`

Except when run, I receive this error:
```
File: super-rentals/templates/test.hbs
An unquoted attribute value must be a string or a mustache, preceeded by whitespace or a '=' character, and followed by whitespace or a '>' character (on line 9)
Error: An unquoted attribute value must be a string or a mustache, preceeded by whitespace or a '=' character, and followed by whitespace or a '>' character (on line 9)
    at assembleAttributeValue (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:18145:17)
    at Parser.exports.default.finishAttributeValue (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:18131:19)
    at Object.EventedTokenizer.states.attributeValueUnquoted (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:20193:25)
    at Object.EventedTokenizer.tokenizePart (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:19891:33)
    at Parser.exports.default.ContentStatement (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:17877:22)
    at Parser.acceptNode (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:18243:27)
    at Parser.exports.default.Program (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:17777:14)
    at Parser.acceptNode (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:18243:27)
    at Object.preprocess (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:18202:46)
    at compileSpec (/Users/michael/Sites/super-rentals/bower_components/ember/ember-template-compiler.js:12697:37)
```

This error is resolved by adding a space after the '}':
`<input type="text" value={{favoriteBand}} onblur={{action "bandDidChange"}} />`
However, the example is valid html.

I filed an issue on the guides to display a non-error causing example, emberjs/guides#1134. But the problem is actually in the template compiler. 

I don't know how the parser actually works, but I believe the function `attributeValueUnquoted` should call `finishAttributeValue()` when it see's a '/' character.

**Comment by stefanpenner** [comment]
Clearly this is intentional, as the error message has been well crafted.

@mmun was there a reason for this choice in grammar? Mostly to simplify or was their some hard limitation?

**Comment by mmun** [comment]
No reason. We should make this work.

**Comment by rwjblue** [comment]
Upstream PR was merged in https://github.com/tildeio/htmlbars/pull/443.
