### ISSUE TITLE
cannot find module 'rsvp'

### ISSUE THREAD

**Issue by shime** [emberjs/ember.js#12819]
Installing ember CLI with 

```
npm install -g ember-cli
```
and then trying to use it with 

```
ember
```
produces the following error
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hrvoje/node_modules/ember-cli/lib/ext/promise.js:3:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

NPM v2.14.4
Node v4.1.2

**Comment by shime** [comment]
Happening on 

NPM v3.3.12
Node v5.4.1

too.

**Comment by shime** [comment]
Closing in favor of [ember-cli#5357](https://github.com/ember-cli/ember-cli/issues/5357)

**Comment by zeiv** [comment]
Heh, just ran into this too on a separate project.
