### ISSUE TITLE
Typo in css file led to a weird error...

### ISSUE THREAD

**Issue by webzorg** [emberjs/ember.js#12868]
Typo  in css file led to a weird error, with pretty much no hint other than it was somehow connected to css file  width: 10px:"  quote being a typo

ember build --environment=production
version: 2.3.0-beta.1
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Build failed.
File: assets/super-rentals.css
body.split is not a function
TypeError: body.split is not a function
    at Optimizer.tokenize (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/properties/optimizer.js:114:23)
    at Object.Optimizer.process (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/properties/optimizer.js:264:20)
    at Optimizer.optimize (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/selectors/optimizer.js:289:40)
    at Object.Optimizer.process (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/selectors/optimizer.js:337:7)
    at Object.optimizeSelectors (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/clean.js:371:10)
    at replace (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/clean.js:104:19)
    at CleanCSS.minify (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/clean.js:365:5)
    at Object.ImportInliner.process.whenDone (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/clean.js:70:25)
    at Inliner.processNext (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/imports/inliner.js:96:22)
    at Object.Inliner.process (/home/webgen/www/ember/super-rentals/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/node_modules/broccoli-clean-css/node_modules/clean-css/lib/imports/inliner.js:77:12)

**Comment by stefanpenner** [comment]
This seems like a bug in broccoli-clean-Css. Could you open an issue there?

**Comment by syit** [comment]
Please go through the section
http://ember-cli.com/user-guide/#asset-compilation
 
Apply the below changes:
minifyCSS: {
      enabled: false
    }
I hope it should work.
