### ISSUE TITLE
{{each}} fails test when attribute is not passed in

### ISSUE THREAD

**Issue by Joelkang** [emberjs/ember.js#12861]
I have a component that loops through an optional attribute

``` handlebars
{{#each attrs.inactiveModels as |model index|}}
 ...
{{/each}}
```

This works fine when running the code, regardless of whether`inactiveModels` is passed in, an empty array, or undefined. However, in tests it's throwing this error when inactiveModels is not passed into the inline hbs component:

``` javascript
TypeError: Cannot read property 'addDependency' of undefined
    at eachParam (http://localhost:7357/assets/vendor.js:18212:11)
    at Object.linkRenderNode (http://localhost:7357/assets/vendor.js:18182:23)
    at Object.linkParams (http://localhost:7357/assets/vendor.js:58195:19)
    at linkParamsAndHash (http://localhost:7357/assets/vendor.js:57394:29)
    at Object.AlwaysDirtyVisitor.block (http://localhost:7357/assets/vendor.js:57407:27)
    at RenderResult.populateNodes (http://localhost:7357/assets/vendor.js:57839:19)
    at RenderResult.render (http://localhost:7357/assets/vendor.js:57776:10)
    at render (http://localhost:7357/assets/vendor.js:57586:18)
    at http://localhost:7357/assets/vendor.js:58413:7
    at renderAndCleanup (http://localhost:7357/assets/vendor.js:58448:18)
```

Changing my code to the following fixed it.

``` handlebars
{{#each inactiveModels as |model index|}}
 ...
{{/each}}
```

If it matters, the body of the each is yields a `{{hash}}`, I'm also on 2.3.0 canary da304cf

**Comment by rwjblue** [comment]
I made a couple JSBin's to try and track this down.

Repro: http://rwjblue.jsbin.com/mocequ/edit?html,js

I'm still digging into what is going on though...

**Comment by rwjblue** [comment]
Repro above is now passing on beta/canary: http://jsbin.com/mocequ/edit?html,js,output
