### ISSUE TITLE
Call to appInstance.lookup in an instance initializer is causing a deprecation warning

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#12949]
I've updated my instance initialiser as pre [the instructions](http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container), but I'm still getting a deprecation warning:

```js
/* global window */
import config from '../config/environment';

export default {
  initialize(appInstance) {
    var service = 'service:ember-devtools';
    var devTools = appInstance.lookup ? appInstance.lookup(service)
        // backwards compatibility < 2.1
        : appInstance.container.lookup(service);
    var devToolsConfig = config['ember-devtools'] || {};
    if (devToolsConfig.global === true) {
      devTools.globalize();
    }
    else if (devToolsConfig.global) {
      window[devToolsConfig.global] = devTools;
    }
  }
};
```

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://ember.dev:4200/assets/vendor.js:16666:7)
        at raiseOnDeprecation (http://ember.dev:4200/assets/vendor.js:16576:12)
        at HANDLERS.(anonymous function) (http://ember.dev:4200/assets/vendor.js:16666:7)
        at invoke (http://ember.dev:4200/assets/vendor.js:16682:7)
        at deprecate (http://ember.dev:4200/assets/vendor.js:16635:32)
        at Object.deprecate (http://ember.dev:4200/assets/vendor.js:26643:37)
        at Object.defineProperty.get (http://ember.dev:4200/assets/vendor.js:12096:26)
        at Function.ClassMixinProps._lazyInjections (http://ember.dev:4200/assets/vendor.js:47174:19)
        at instantiate (http://ember.dev:4200/assets/vendor.js:12051:34)
```

**Comment by rwjblue** [comment]
This looks generally correct, do you have a demo repo that I can look at?

**Comment by aexmachina** [comment]
Thanks @rwjblue, it was actually coming from elsewhere in the code.
