### ISSUE TITLE
Master branch no longer builds in NPM on Windows

### ISSUE THREAD

**Issue by AmazingJaze** [emberjs/ember.js#12973]
This started happening 2 - 3 weeks ago.  Repro's on many versions of Node and NPM, including the latest versions.

**NOTE** Build still works fine in Windows for EmberJS 2.3.0.

### Repro Stes
git clone https://github.com/emberjs/ember.js master --recursive
cd master
git checkout master
npm install
npm run build

### Result
![image](https://cloud.githubusercontent.com/assets/6732159/13091653/111ae2b6-d4b1-11e5-9dcb-9c2bdc26f644.png)

**Comment by AmazingJaze** [comment]
**Edit:** fixed repro steps inline ^

**Comment by rwjblue** [comment]
During the tildeio/glimmer integration we are using symlinks in the repo to ensure that we can share tests (without duplicating).  I believe that on windows you need to enable a custom permissions to enable symlinks.  The ember-cli guide on Windows might help:

* http://ember-cli.com/user-guide/#windows
* http://ember-cli.com/user-guide/#symlinks-on-windows

**Comment by btecu** [comment]
Also, if you run as Administrator, you have `symlink permission`.

**Comment by rwjblue** [comment]
After looking at the error in the screenshot again, I'm not certain this is related to symlinking and whatnot.  Seems more like `npm` permission issues.

**Comment by AmazingJaze** [comment]
@zackhall confirmed he was able to build master in Windows from an elevated command prompt.

**Comment by stefanpenner** [comment]
> During the tildeio/glimmer integration we are using symlinks in the repo to ensure that

i thought this came via the normal broccoli stuff? Maybe this changed..

What we can do, is use symlink or junction depending on platform, if we are merely linking dirs, which may do the trick for us.

**Comment by rwjblue** [comment]
> I thought this came via the normal broccoli stuff? Maybe this changed..

The build itself is not the issue (we are using normal broccoli stuff as you mentioned). During the migration, we are moving test files from packages/ember-htmlbars to packages/ember-glimmer, and when we move them we symlink the file back to its original location so that the tests are ran for htmlbars and for glimmer.

**Comment by zackhall** [comment]
I believe that this is related to [npm/npm/issues/9696](https://github.com/npm/npm/issues/9696). 

I tried installing on a new VM and it failed. Then, using the `--force` flag worked as a successful mitigation.

Here's my errors, which seem to mirror the errors described in the issue.
```
391493 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json.3048548e055c94f00f828bc1844b57b3' -> 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json'
391493 verbose stack     at Error (native)
391494 verbose cwd C:\dev\ember.js
391495 error Windows_NT 10.0.14270
391496 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
391497 error node v4.3.1
391498 error npm  v2.14.12
391499 error path C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json.3048548e055c94f00f828bc1844b57b3
391500 error code EPERM
391501 error errno -4048
391502 error syscall rename
391503 error Error: EPERM: operation not permitted, rename 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json.3048548e055c94f00f828bc1844b57b3' -> 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json'
391503 error     at Error (native)
391503 error  { [Error: EPERM: operation not permitted, rename 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json.3048548e055c94f00f828bc1844b57b3' -> 'C:\Users\zackhall\AppData\Roaming\npm-cache\minimatch\2.0.10\package\package.json']
391503 error   errno: -4048,
391503 error   code: 'EPERM',
391503 error   syscall: 'rename',
391503 error   path: 'C:\\Users\\zackhall\\AppData\\Roaming\\npm-cache\\minimatch\\2.0.10\\package\\package.json.3048548e055c94f00f828bc1844b57b3',
391503 error   dest: 'C:\\Users\\zackhall\\AppData\\Roaming\\npm-cache\\minimatch\\2.0.10\\package\\package.json',
391503 error   parent: 'matcher-collection' }
391504 error Please try running this command again as root/Administrator.
391505 verbose exit [ -4048, true ]
```

**Comment by zackhall** [comment]
After getting past this with the `--force` param I saw some other errors during `npm run build`. 

Building fails because [ember-cli-build.js#L46-47](https://github.com/emberjs/ember.js/blob/master/ember-cli-build.js#L46-L47) requires `broccoli-stew` but it's not included in the [package.json](https://github.com/emberjs/ember.js/blob/master/package.json).

```
BuildingCould not require 'ember-cli-build.js': Cannot find module 'broccoli-stew'
Error: Could not require 'ember-cli-build.js': Cannot find module 'broccoli-stew'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dev\ember\ember-cli-build.js:46:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\dev\ember\node_modules\ember-cli\lib\utilities\find-build-file.js:21:17)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\dev\ember\node_modules\ember-cli\lib\models\builder.js:49:21)
    at Class.module.exports.Task.extend.init (C:\dev\ember\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\dev\ember\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\dev\ember\node_modules\ember-cli\lib\tasks\build.js:15:19)

npm ERR! Windows_NT 10.0.14270
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! ember@2.5.0-canary build: `ember build --environment production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember@2.5.0-canary build script 'ember build --environment production'.
npm ERR! This is most likely a problem with the ember package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment production
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ember\npm-debug.log
```

**Comment by rwjblue** [comment]
The reason that this is not failing for CI (or myself locally) is that when using npm@3 most of the deps are at the top level `node_modules` path (and therefore `node_modules/broccoli-stew` is present).  I see you are using npm@2 which does not have this behavior, and catches that we have a bug here...

@zackhall - Would love a PR adding `broccoli-stew` to `devDependencies` here.

**Comment by rwjblue** [comment]
@zackhall - Actually @stefanpenner did this in https://github.com/emberjs/ember.js/pull/12994...

**Comment by zackhall** [comment]
Awesome, thanks for the follow up @rwjblue and @stefanpenner. This does fix it in npm2. 

I'm currently trying to build in a few clean VMs using npm 2 and npm 3 with Windows 10. It's failing for both yet. This is preventing us from running the tests against the newest builds of Edge to ensure we don't regress ember.js with new checkins.

I've ensured that I've enabled [symlinks for windows](http://ember-cli.com/user-guide/#symlinks-on-windows) and I've tried both cmd and powershell as an Admin to build.

Unfortunately with all of these methods I'm still getting the same issue. This is pointing to an unexpected token in the symlink file [/ember-htmlbars/helpers/concat.js](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/helpers/concat.js).  

```
> ember build --environment production

version: 2.3.0
Build failed.
File: ember-htmlbars/helpers/concat.js
ember-htmlbars/helpers/concat.js: Unexpected token (1:0)
SyntaxError: ember-htmlbars/helpers/concat.js: Unexpected token (1:0)
> 1 | ../../../ember-glimmer/lib/helpers/concat.js
    | ^
    at Parser.pp.raise (C:\dev\ember.js\node_modules\babylon\lib\parser\location.js:24:13)
    at Parser.pp.unexpected (C:\dev\ember.js\node_modules\babylon\lib\parser\util.js:82:8)
    at Parser.pp.parseExprAtom (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:425:12)
    at Parser.pp.parseExprSubscripts (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:236:19)
    at Parser.pp.parseMaybeUnary (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:217:19)
    at Parser.pp.parseExprOps (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:163:19)
    at Parser.pp.parseMaybeConditional (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:145:19)
    at Parser.pp.parseMaybeAssign (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:112:19)
    at Parser.pp.parseExpression (C:\dev\ember.js\node_modules\babylon\lib\parser\expression.js:79:19)
    at Parser.pp.parseStatement (C:\dev\ember.js\node_modules\babylon\lib\parser\statement.js:137:23)
    at Parser.pp.parseTopLevel (C:\dev\ember.js\node_modules\babylon\lib\parser\statement.js:30:21)
    at Parser.parse (C:\dev\ember.js\node_modules\babylon\lib\parser\index.js:70:17)
    at Object.parse (C:\dev\ember.js\node_modules\babylon\lib\index.js:45:50)
    at Object.exports.default (C:\dev\ember.js\node_modules\babel-core\lib\helpers\parse.js:36:18)
    at File.parse (C:\dev\ember.js\node_modules\babel-core\lib\transformation\file\index.js:574:40)
    at File.parseCode (C:\dev\ember.js\node_modules\babel-core\lib\transformation\file\index.js:691:20)

npm ERR! Windows_NT 10.0.14271
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! ember@2.5.0-canary build: `ember build --environment production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember@2.5.0-canary build script 'ember build --environment production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ember package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ember
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ember
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ember.js\npm-debug.log
```

**Comment by zackhall** [comment]
I've found the issue and gotten an ember build that I can run and test on Windows 10! :tada:

Running the following from the cloned repo's directory enabled the build to run properly and pass:

```
git config core.symlinks true
git reset --hard HEAD
```
