### ISSUE TITLE
ember server - Huge error

### ISSUE THREAD

**Issue by oisteinhaugland** [emberjs/ember.js#13055]
Hi! 

I'm just starting out with ember and i've run in to a problem when using the `ember serve `command.``

i ran 
```

npm install -g ember-cli
npm install -g phantomjs
npm new test1
cd test1
ember server
```

and get the following error message:
```

version: 2.4.1
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: modules/ember-ajax/errors.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/ember-ajax/errors.js: Unknown option: /Users/Rubbelogbit/.babelrc.presets
    at Logger.error (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:94:21)
    at Babel.processString (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:123:25)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new Babel (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli-babel/index.js:21:52)
    at /Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at Class.Addon.preprocessJs (/Users/Rubbelogbit/Desktop/myWebsites/test1/node_modules/ember-cli/lib/models/addon.js:682:23)
```

And honestly, i have no idea what to do to fix it. I have been googling the problem for a few hours with now luck.
Any suggestions?

**Comment by stefanpenner** [comment]
> ReferenceError: [BABEL] modules/ember-ajax/errors.js: Unknown option: /Users/Rubbelogbit/.babelrc.presets

this file should likely be removed

**Comment by oisteinhaugland** [comment]
/Users/Rubbelogbit/.babelrc.presets doesnt exist apparently

**Comment by stefanpenner** [comment]
does `/Users/Rubbelogbit/.babelrc` ?

**Comment by rwjblue** [comment]
Also, this is likely not an issue with ember itself so we should move this issue over to ember-cli/ember-cli.

**Comment by stefanpenner** [comment]
oops didn't notice the repo..

**Comment by oisteinhaugland** [comment]
Ok. i'm pretty new to github aswell so how do i move the issue? or do i just make a copy to ember-cli/ember-cli?

**Comment by rwjblue** [comment]
Ahh, sorry about that. Yeah, you would open a new issue up with these details in that repo.

**Comment by oisteinhaugland** [comment]
Got it. Thanks!

**Comment by stefanpenner** [comment]
@oisteinhaugland please be sure to read: https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md

**Comment by oisteinhaugland** [comment]
@stefanpenner thanks. I'll it post up on stackoverflow

**Comment by daltonamitchell** [comment]
In case you're still having the issue, you need to delete the file `~/.babelrc`. It's not needed when using `broccoli-babel-transpiler` at the current version.

See the [SO answer](http://stackoverflow.com/a/36093045/2620729) for more details :)
