### ISSUE TITLE
Building docs fails

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#13247]
While running `ember ember-cli-yuidoc` part of build, getting:

```
info: Rendering and writing 93 class pages.
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: TypeError: t[o].call is not a function
    at a (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:197)
    at e.each (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
    at Object.Y.DocBuilder.augmentData (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:651:15)
    at /Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1283:34
    at Array.forEach (native)
    at /Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1231:28
    at prepare (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/utils.js:222:9)
    at Object.Y.DocBuilder.renderClass (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1142:15)
    at null.<anonymous> (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1527:75)
    at Function.O.each (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js:3309:16)
    at a (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:319)
    at e.each (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
    at Object.Y.DocBuilder.writeComponents (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1523:15)
    at null.<anonymous> (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1763:38)
    at /Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/node_modules/yui/parallel/parallel-min.js:1:430
    at null.<anonymous> (/Users/gmunjal/code/emberjs/ember.js/node_modules/ember-cli-yuidoc/node_modules/yuidocjs/lib/builder.js:1052:17)
error: --------------------------------------------------------------------------
error: Node.js version: v4.2.2
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.0
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```

This is on master branch.

**Comment by stefanpenner** [comment]
@Gaurav0 can you share, os / node version / npm version etc. ? This will help anyone who debugs further.

**Comment by Gaurav0** [comment]
OS: Mac OS/X Yosemite 10.10.5
node: 4.2.2
npm: 2.14.10

**Comment by stefanpenner** [comment]
@Gaurav0 thanks

**Comment by toddjordan** [comment]
we did merge a yuidoc postprocessing update recently for feature-flagged code.  Trying to reproduce to make sure its not because of that.

**Comment by toddjordan** [comment]
Removed the yuidoc preprocessor for feature-flags recently added, but still get the error.
