### ISSUE TITLE
beta & release channels broken due to changes from #13239

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13298]
Error message:

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at _warnIfUsingStrippedFeatureFlags (/home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:1529:25)
    at /home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:1547:5
    at internalRequire (/home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:98:16)
    at requireModule (/home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:44:14)
    at /home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:20781:1
    at Object.<anonymous> (/home/travis/build/jonathanKingston/ember-cli-eslint/bower_components/ember/ember-template-compiler.js:20784:2)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Class.module.exports.included (/home/travis/build/jonathanKingston/ember-cli-eslint/node_modules/ember-cli-htmlbars-inline-precompile/index.js:17:20)
    at EmberAddon.<anonymous> (/home/travis/build/jonathanKingston/ember-cli-eslint/node_modules/ember-cli/lib/broccoli/ember-app.js:413:15)
    at Array.filter (native)
```

**Comment by rwjblue** [comment]
Whoops! Duplicate of https://github.com/emberjs/ember.js/issues/13297.
