### ISSUE TITLE
Current Release and current Ember-beta cannot build

### ISSUE THREAD

**Issue by EWhite613** [emberjs/ember.js#13297]
Using the newest release `2.4.4+0947bfc3`  to build I get the following error with ember-try (https://github.com/ember-cli/ember-try/issues/72):

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at _warnIfUsingStrippedFeatureFlags (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:1529:25)
    at /localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:1547:5
    at internalRequire (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:98:16)
    at requireModule (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:44:14)
    at /localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:20781:1
    at Object.<anonymous> (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:20784:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Class.module.exports.included (/localdisk/workspace/ember-frost-core/node_modules/ember-cli-htmlbars-inline-precompile/index.js:17:20)
    at EmberAddon.<anonymous> (/localdisk/workspace/ember-frost-core/node_modules/ember-cli/lib/broccoli/ember-app.js:413:15)
    at Array.filter (native)
```

As @rwjblue  suggests this may be 

> an issue with emberjs/ember.js@a61e6a9, which was cherry picked from emberjs/ember.js#13239.

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember.js/pull/13299

**Comment by rwjblue** [comment]
I just pushed https://github.com/emberjs/ember.js/pull/13299 to both release and beta branches, which should fix things up (will take ~ 10-15 minutes for Travis to update the bower repo).
