### ISSUE TITLE
Cannot set property 'EXTEND_PROTOTYPES' of undefined while compiling templates.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13347]
The following error is generated while compiling templates in an Ember CLI app using canary:

```
Cannot set property 'EXTEND_PROTOTYPES' of undefined
TypeError: Cannot set property 'EXTEND_PROTOTYPES' of undefined
    at /Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/utils.js:23:43
    at Array.forEach (native)
    at Object.module.exports.initializeEmberENV (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/utils.js:20:13)
    at TemplateCompiler.initializeFeatures (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/index.js:64:9)
    at new TemplateCompiler (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/index.js:29:8)
    at TemplateCompiler (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/index.js:12:12)
    at Object.registry.add.toTree (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:16)
    at /Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/rjackson/Source/sandbox/ember-cli/sample-2-4-3/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
```

---

Steps to reproduce in ember-cli:

```
ember new foo
cd foo
bower install --save ember#canary
ember build
```

---

This was introduced by #13319, I am working on a fix now.

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/13348.

**Comment by rwjblue** [comment]
The mutation of `Ember.ENV` by ember-cli-htmlbars is addressed in https://github.com/ember-cli/ember-cli-htmlbars/pull/70.
