### ISSUE TITLE
[Beta] TemplateCompiler error after updating to 2.6.0-beta.1

### ISSUE THREAD

**Issue by medokin** [emberjs/ember.js#13370]
Hi, I get the following error after the update from 2.5.0 to 2.6.0-beta.1:

```
c:\dev\ember\base-webapp>ember s
Livereload server on http://localhost:49156
Serving on http://localhost:4200/
File: webapp/pods/admin/categories/category/template.hbs
The Broccoli Plugin: [TemplateCompiler] failed with:
TypeError: Cannot read property 'start' of null
    at Object.calculateLocationDisplay [as default] (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:12780:19)
    at assertPath (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:11855:196)
    at c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:11823:7
    at Walker.visit (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18840:7)
    at visitors.ElementNode (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18856:16)
    at Walker.children (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18873:7)
    at Walker.visit (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18841:12)
    at visitors.ElementNode (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18856:16)
    at Walker.children (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18873:7)
    at Walker.visit (c:\dev\ember\base-webapp\bower_components\ember\ember-template-compiler.js:18841:12)

The broccoli plugin was instantiated at:
    at TemplateCompiler.Plugin (c:\dev\ember\base-webapp\node_modules\broccoli-plugin\index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (c:\dev\ember\base-webapp\node_modules\broccoli-persistent-filter\index.js:38:10)
    at new TemplateCompiler (c:\dev\ember\base-webapp\node_modules\ember-cli-htmlbars\index.js:20:10)
    at TemplateCompiler (c:\dev\ember\base-webapp\node_modules\ember-cli-htmlbars\index.js:12:12)
    at Object.registry.add.toTree (c:\dev\ember\base-webapp\node_modules\ember-cli-htmlbars\ember-addon-main.js:31:16)
    at c:\dev\ember\base-webapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (c:\dev\ember\base-webapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:182:11)
    at module.exports.preprocessTemplates (c:\dev\ember\base-webapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:165:10)
    at EmberApp._processedTemplatesTree (c:\dev\ember\base-webapp\node_modules\ember-cli\lib\broccoli\ember-app.js:802:48)
```

Does someone has an idea where i should start looking for the cause?

Ember: 2.6.0-beta.1
Cli: 2.4.3
OS: Win10

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/13312, which is included in the `beta` branch and will be released as v2.6.0-beta.2.

**Comment by rwjblue** [comment]
You can update to latest `beta` channel build via `bower install --save ember#beta`, or just wait until 2.6.0-beta.2 is released.  Sorry about the troubles.

**Comment by medokin** [comment]
Ah ok. Issue was opened under `canary`, I searched only for beta issues... 
No trouble at all 
Thanks :+1:
