### ISSUE TITLE
 Ember Data Request GET /cases returned 

### ISSUE THREAD

**Issue by smitakiran25** [emberjs/ember.js#13662]
I am using ember cli 2.6 version 
OS: fedora 20
npm:3.9.2
bower version: 1.7.9

I am getting the following error
ember.debug.js:31387 Error: Ember Data Request GET /cases returned a 404
Payload (text/html; charset=utf-8)
Cannot GET /cases

    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25183:21)
    at Error.AdapterError (http://localhost:4200/assets/vendor.js:76168:16)
    at Class.handleResponse (http://localhost:4200/assets/vendor.js:77417:14)
    at Class.hash.error (http://localhost:4200/assets/vendor.js:77506:29)
    at fire (http://localhost:4200/assets/vendor.js:3403:30)
    at Object.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3515:7)
    at done (http://localhost:4200/assets/vendor.js:8570:14)
    at XMLHttpRequest.<anonymous> (http://localhost:4200/assets/vendor.js:8909:9)

model/case.js
![image](https://cloud.githubusercontent.com/assets/11611902/16008130/03535826-3194-11e6-81a6-607d1d6b1bf5.png)

**Comment by Gaurav0** [comment]
Can you create an (ember-twiddle)[https://ember-twiddle.com] ?

**Comment by DanChadwick** [comment]
@smitakiran25 - You asked for your backend the retrieve all the cases with
```
return this.get('store').findAll('case');
```
And your backend returned a 404 (resource not found). Is there are reason you aren't looking at your backend to see why it is returning a 404? I'm not sure why this is an ember.js issue. Can you elaborate?

**Comment by btecu** [comment]
This likely can be closed. Wrong project.

**Comment by smitakiran25** [comment]
Thank you all, I solved this problem it was a database issue

**Comment by mehrajpasha** [comment]
what is the database issue..I'm getting the same error...my adapter file `
import DS from 'ember-data';
import PouchDB from 'pouchdb';
import config from '../config/environment';
import { JSONAPIAdapter } from 'ember-pouch';
var remote = new PouchDB('http://localhost:5984/node');
var db = new PouchDB('node');
const { assert, isEmpty } = Ember;
/*var get = Ember.get, set = Ember.set;*/
db.sync(remote, {
   live: true,   // do a live, ongoing sync
   retry: true   // retry if the conection is lost
});
export default DS.JSONAPIAdapter.extend({
  db:db
}`

**Comment by mehrajpasha** [comment]
what is the database issue..I'm getting the same error...my adapter file
![screenshot 250](https://user-images.githubusercontent.com/20518128/33980384-ae8b6770-e0ce-11e7-8c6a-f06dd079e1d7.png)

**Comment by oneman93** [comment]
I had 500 error from Lumen web service whatever data I give from Ember js. Later on I found that my table requires to have created_at, updated_at timestamp to work properly. So if API doesn't match with database, you can have 500 error on Ember side.
