### ISSUE TITLE
Error accessing block params > number of yielded items

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13994]
Given the following templates:

```hbs
{{#foo-bar as |hola index|}}
  {{hola}} - {{index}}
{{/foo-bar}}
```

```hbs
{{! app/templates/components/foo-bar.hbs }}

{{yield "hi"}}
```

The following error is triggered:

```
TypeError: Cannot read property 'tag' of undefined
    at new MapperReference (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:40994:33)
    at Object.map (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:41010:16)
    at OptimizedCautiousAppendOpcode.normalize (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:44144:38)
    at OptimizedCautiousAppendOpcode.evaluate (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:43807:35)
    at VM.execute (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:49871:28)
    at Template.render (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:49397:23)
    at render (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:10152:46)
    at runInTransaction (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:20178:9)
    at transaction (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:10174:27)
    at Renderer._transaction (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:10181:11)
```

[Demo here](https://jsbin.com/mosise/edit?html,js,output)

**Comment by rwjblue** [comment]
Should be addressed by https://github.com/tildeio/glimmer/pull/275.
