### ISSUE TITLE
Using `component` as a yielded block param leads to bizarre error condition.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14096]
Using the word `component` as a yielded block param leads to a very odd error message in glimmer2.

Sample invocation:

```hbs
{{#foo-bar as |component|}}
  {{component.title}}
{{/foo-bar}}
```

Error:

```
Error: Assertion Failed: You cannot create a component from null using the {{component}} helper
    at assert (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:5682:13)
    at Object.assert (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:14586:34)
    at ClosureComponentReference.compute (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:8855:26)
    at ClosureComponentReference.value (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:12095:45)
    at GuardedCautiousAppendOpcode.evaluate (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:43893:51)
    at VM.execute (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:49785:28)
    at Template.render (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:49318:23)
    at render (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:10093:46)
    at runInTransaction (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:20230:9)
    at transaction (https://s3.amazonaws.com/builds.emberjs.com/alpha/ember.debug.js:10115:27)
```

[Demo JSBin](https://jsbin.com/tavofu/edit?html,js,output)

**Comment by rwjblue** [comment]
There are at least a few different possibilities here:

1. Make it "just work".
2. Assert when using a block param name that is "reserved" (any of our internal helpers names).
3. Other?

---
I would prefer 1) above, but am unsure exactly how easy/hard that would be in tildeio/glimmer.

We should also fix the `{{component` helper to have a better assertion when no argument is specified at all (as opposed to an argument of `null` or `undefined`).

**Comment by rwjblue** [comment]
#14141 will fix this issue
