### ISSUE TITLE
Helpers mutating `hash` may error if no hash was provided.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14189]
One optimization that the Glimmer engine does is to avoid creating objects when it does not need to. An example of this can be seen when evaluating helper and/or component invocations where there is no hash arguments.  Such as this:

```hbs
{{page-title "My App"}}
```

In order to avoid creating a wasted hash argument here, Glimmer will use a custom `EVALUATED_EMPTY_NAMED_ARGS` which always returns a shared constant named `EMPTY_DICT`.  In order to prevent that shared constant from being mutated, the engine uses `Object.freeze(EMPTY_DICT)`.

All of these assumptions/steps are completely reasonable.  Unfortunately, where this falls down is when a helper (such as [ember-page-title](https://github.com/tim-evans/ember-page-title/blob/3d9584736f3c04f3d327faf6ae07121b5fd8ae3b/addon/helpers/page-title.js#L21)) mutate that provided hash argument.  If you do this, the following error is triggered:

```
TypeError: Can't add property foo, object is not extensible
    at https://output.jsbin.com/solokun:55:12
    at Function.create (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:12837:22)
    at https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:8301:69
    at CompiledHelper.evaluate (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:42855:20)
    at VM.evaluateOperand (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:50094:40)
    at PutValueOpcode.evaluate (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:45494:16)
    at VM.execute (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:50066:28)
    at Template.render (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:49616:23)
    at RootState.render (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:9969:61)
    at runInTransaction (https://s3.amazonaws.com/builds.emberjs.com/canary/ember.debug.js:20692:28)
```

[JSBin Demo Here](https://jsbin.com/solokun)

---

We need to decide if we must "fix" this by providing a custom hash object to each helper invocation (less than ideal because we would much prefer to benefit from doing less work).

**Comment by rwjblue** [comment]
@chancancode - Need your thoughts on this...

**Comment by ef4** [comment]
I'm not feeling super sympathetic on this one. Mutating your arguments is usually a bad.

It's unfortunate that we can't easily provide consistent behavior: either _always_ give you a frozen hash (whether or not it's empty), or always give you a copy that is yours to abuse. Either of those choices sound expensive in terms of allocations.

**Comment by rwjblue** [comment]
@ef4 - Perhaps we could freeze/seal all params and hash when in debug only? That would provide a fairly common footing but still avoid the extra cost in production...

**Comment by chancancode** [comment]
Yeah. I think I agree with @ef4. The debugSeal idea seems good if it's not very slow?

**Comment by Turbo87** [comment]
FWIW the problem in ember-page-title has been resolved already: https://github.com/tim-evans/ember-page-title/pull/41
