### ISSUE TITLE
You must use Ember.set() to set the `parentView` property (of <tiny@component:em-select::ember1505>) to `null`.

### ISSUE THREAD

**Issue by GCorbel** [emberjs/ember.js#14260]
I upgraded an ember app to the Ember 2.8 version and I have this error :

```
Error: Assertion Failed: You must use Ember.set() to set the `parentView` property (of <tiny@component:em-select::ember1505>) to `null`.
    at new Error (native)
    at Error.EmberError (http://test.local.com:4201/assets/vendor.js:28666:21)
    at assert (http://test.local.com:4201/assets/vendor.js:16366:13)
    at Object.assert (http://test.local.com:4201/assets/vendor.js:28478:34)
    at Class.SETTER_FUNCTION [as parentView] (http://test.local.com:4201/assets/vendor.js:32482:26)
    at Array.<anonymous> (http://test.local.com:4201/assets/vendor.js:19915:25)
    at didCleanupTree (http://test.local.com:4201/assets/vendor.js:20266:15)
    at Object.clearMorph (http://test.local.com:4201/assets/vendor.js:56563:7)
    at RenderResult.destroy (http://test.local.com:4201/assets/vendor.js:55867:32)
    at Renderer.remove (http://test.local.com:4201/assets/vendor.js:24226:18)
```

The error is on [this line](https://github.com/emberjs/ember.js/blob/v2.8.0/packages/ember-htmlbars/lib/hooks/cleanup-render-node.js#L21). What can I do?

**Comment by rwjblue** [comment]
Observing `parentView` isn't really something we support. Can you share more information about your use case?

**Comment by GCorbel** [comment]
The error comes from here : https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/mixins/in-form.js#L7 .

I think we can use something else than `computed` to have the same behavior.

Thanks @rwjblue .
