### ISSUE TITLE
Tests fail on Windows 10

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#14276]
Today's master branch (64d23c0f9b5aad88f1d083bd1d22eaad4ad5112b)
Tests completed in 17332 milliseconds.
6652 assertions of 19447 passed, 12795 failed.

**Comment by BryanCrotaz** [comment]
Lots fail with 
`afterEach failed on An invalid factory throws an error: Cannot read property 'currentRunLoop' of undefined`

and 
```
beforeEach failed on `click` triggers appropriate events in order: Attempting to register an unknown factory: 'service:-routing'@ 8 ms
Source: 	
TypeError: Attempting to register an unknown factory: 'service:-routing'
    at Object.register (http://localhost:4200/ember.debug.js:1836:15)
    at commonSetupRegistry (http://localhost:4200/ember.debug.js:4873:14)
    at Function.buildRegistry [as _super] (http://localhost:4200/ember.debug.js:4782:7)
    at Function.buildRegistry (http://localhost:4200/ember.debug.js:4124:34)
    at Function.superWrapper [as buildRegistry] (http://localhost:4200/ember.debug.js:38086:22)
    at Class.buildRegistry (http://localhost:4200/ember.debug.js:4525:59)
    at Class.init (http://localhost:4200/ember.debug.js:4482:12)
    at Class.superWrapper [as init] (http://localhost:4200/ember.debug.js:38086:22)
    at Class.init (http://localhost:4200/ember.debug.js:3528:19)
    at Class.superWrapper [as init] (http://localhost:4200/ember.debug.js:38086:22)
```

**Comment by BryanCrotaz** [comment]
Same branch passes on Travis

**Comment by rwjblue** [comment]
What browser?

**Comment by rwjblue** [comment]
We are testing against many browsers (Chrome, FireFox, IE9, IE10, IE11, Edge, Safari Current, Safari Last) in our CI, so it is somewhat surprising that the test suite doesn't pass (I'm assuming you are running the tests with at least one of those browsers).

**Comment by BryanCrotaz** [comment]
Chrome

**Comment by Serabe** [comment]
@BryanCrotaz is this still happening with latest master?

**Comment by Serabe** [comment]
@BryanCrotaz can you check please if this is still going on with latest master. Thank you!

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can follow up on this.

Thank you!
