### ISSUE TITLE
[Glimmer2] positional params error

### ISSUE THREAD

**Issue by dwickern** [emberjs/ember.js#14416]
```
{{input foo bar}}
```
The template code is nonsense, and this was a bug in my app. I'm only opening an issue because this causes a nasty error in ember internals.

[Twiddle](https://ember-twiddle.com/b59865e60f45364376bd4554457fc2af?openFiles=templates.application.hbs%2C) (compare Ember 2.8.0 vs beta)

In Ember 2.8 and earlier, the positional params are ignored. In 2.9.0-beta4, this error happens:
```
TypeError: Cannot read property 'length' of undefined
    at https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:10895:59
    at runInDebug (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:5818:5)
    at Object.runInDebug (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:15416:38)
    at validatePositionalParameters (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:10885:17)
    at CurlyComponentManager.prepareArgs (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:11017:7)
    at OpenComponentOpcode.evaluate (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:44159:32)
    at VM.execute (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:50641:28)
    at Object.render (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:50222:23)
    at RootState.render (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:10321:46)
    at runInTransaction (https://s3.amazonaws.com/builds.emberjs.com/beta/ember.debug.js:20802:28)
```

**Comment by chadhietala** [comment]
Fixed by #14417
