### ISSUE TITLE
JSON-API AssertionError with JSONSerializer

### ISSUE THREAD

**Issue by maha99tests** [emberjs/ember.js#14496]
I've switched my serializer by adding the application serializer file -> app/serializers/application.js

    import DS from 'ember-data';

    export default DS.JSONSerializer.extend({
    });

and I'm using the RESTAdapter, customized at app/adapters/application.js

    export default DS.RESTAdapter.extend({
       host: 'http://60.60.60.60:3000/'
    });

But when my server fails with validation errors with a 422, I get an assertion error that the errors should be in the JSON API format

    ember.debug.js:19157 Error: Assertion Failed: `AdapterError` expects json-api formatted errors array.
    at new Error (native)
    at Error.EmberError (http://60.60.60.60:4200/assets/vendor.js:29613:21)
    at assert (http://60.60.60.60:4200/assets/vendor.js:17311:13)
    at Object.assert (http://60.60.60.60:4200/assets/vendor.js:29425:34)
    at assert (http://60.60.60.60:4200/assets/vendor.js:66105:37)
    at ErrorClass (http://60.60.60.60:4200/assets/vendor.js:77100:41)
    at Class.handleResponse (http://60.60.60.60:4200/assets/vendor.js:78331:16)
    at ajaxError (http://60.60.60.60:4200/assets/vendor.js:78852:25)
    at Class.hash.error (http://60.60.60.60:4200/assets/vendor.js:78426:23)
    at fire (http://60.60.60.60:4200/assets/vendor.js:3617:31)

**Comment by Serabe** [comment]
Can you please move it [emberjs/data](https://github.com/emberjs/data) and add the error payload you are sending?

Thank you!

**Comment by Serabe** [comment]
Wrong button. I'll close it after you have move it to the Ember Data repo. Thank you!

**Comment by maha99tests** [comment]
Moved, and closing issue
