### ISSUE TITLE
Click helper makes  all my tests failing

### ISSUE THREAD

**Issue by Padchi** [emberjs/ember.js#14730]
After upgrading from Ember 2.8 -> 2.9, CLI 2.8 -> 2.9 and ember-cli-qunit 2.1 -> 3.0.4 all my acceptence tests thats use the `click` helper with `.then()` is throwing some weird error. If i skip the `.then()` everything works like expected. 

```
import { test } from 'qunit';
import moduleForAcceptance from 'app/tests/helpers/module-for-acceptance';

moduleForAcceptance('Acceptance | posts');

test('visiting /logga-in', function(assert) {
  visit('/posts');

  click('.btn'').then(function() {
    assert.ok(true, 'This works');
  });
});
```
```
Assertion after the final `assert.async` was resolved@ 310 ms
Source: 	
    at Assert.ok (http://localhost:7357/assets/test-support.js:4186:10)
    at http://localhost:7357/assets/tests.js:379:14
    at isolate (http://localhost:7357/assets/vendor.js:53599:17)
    at http://localhost:7357/assets/vendor.js:53555:16
    at tryCatch (http://localhost:7357/assets/vendor.js:73026:12)
    at invokeCallback (http://localhost:7357/assets/vendor.js:73038:13)
    at publish (http://localhost:7357/assets/vendor.js:73009:7)
    at http://localhost:7357/assets/vendor.js:52488:16
This works
```

**Comment by robbiepitts** [comment]
You might refactor to:

```
test('visiting /logga-in', function(assert) {
  visit('/posts');

  click('.btn'')
  andThen(function() {
    assert.ok(true, 'This works');
  });
});
```

If not you need to tell QUnit to wait for your promise to resolve before finishing the test:

```
test('visiting /logga-in', function(assert) {
  let done = assert.async();
  visit('/posts');

  click('.btn'').then(function() {
    assert.ok(true, 'This works');
    done();
  });
});
```

**Comment by Padchi** [comment]
Ah thanks! Maybe the docs should be updated to explain that you need to do this id you use the click promise.
