### ISSUE TITLE
'ember new' fails on Windows

### ISSUE THREAD

**Issue by edoloughlin** [emberjs/ember.js#14819]
I've tried this on Cygwin and from a CMD prompt with the same result:

```
C:\Users\me\git\ember>ember new test-app
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app\app.js
  create app\components\.gitkeep
  create app\controllers\.gitkeep
  create app\helpers\.gitkeep
  create app\index.html
  create app\models\.gitkeep
  create app\resolver.js
  create app\router.js
  create app\routes\.gitkeep
  create app\styles\app.css
  create app\templates\components\.gitkeep
  create bower.json
  create config\environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\crossdomain.xml
  create public\robots.txt
  create testem.js
  create tests\.jshintrc
  create tests\helpers\destroy-app.js
  create tests\helpers\module-for-acceptance.js
  create tests\helpers\resolver.js
  create tests\helpers\start-app.js
  create tests\index.html
  create tests\integration\.gitkeep
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep
Successfully initialized git.
Installed packages for tooling via npm.
Error creating new application. Removing generated directory `./test-app`
Package ember not found
Error: Package ember not found
    at createError (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\util\createError.js:4:15)
    at C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\core\resolverFactory.js:206:23
    at _fulfilled (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:796:13)

    at C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:137:13)
    at flush (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I had to remove and reinstall bower (npm install -g bower) to get to this point. I'm using npm 3.10.8 and node 6.9.1

**Comment by Turbo87** [comment]
@edoloughlin there has been a GitHub outage this morning, which also affected Bower. Could you please try again and report back whether this is still an issue for you?

**Comment by rwjblue** [comment]
Closing (assuming that was the issue), but I'm happy to reopen if that didn't resolve things for you.
