### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by shamcode** [emberjs/ember.js#15113]
There is the TypeError when you overriden computed property in component with array of `hash` elements. 
Exception:
```
TypeError: Cannot convert object to primitive value
    at Array.toString (native)
    at Object.toString (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:40911:18)
    at Object.set (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:22479:131)
    at ComputedProperty.computedPropertyClobberSet [as clobberSet] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:17428:29)
    at ComputedProperty.computedPropertySetEntry [as set] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:17411:19)
    at new Class (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:36565:22)
    at Function._ClassMixinProps.create (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:36775:12)
    at instantiate (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:1706:23)
    at DeprecatedFactoryManager.create (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:1839:14)
    at Proxy.create (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:1405:22)
```
[Twiddle with error](https://ember-twiddle.com/e18d6f7636b3815e762159ae82d9701c)
[Twiddle without error (replace hash helper to custom)](https://ember-twiddle.com/ea790324b004df88e185ec822cb14d85)
[Twiddle without error (replace computed to plain object)](https://ember-twiddle.com/448ca6401cbd56dc5c5fbabc5f8ade3f)

Exception in dev-tools:
![ember-type-error](https://cloud.githubusercontent.com/assets/2228977/24756038/93bf58d6-1b06-11e7-880c-e78fe04a4ee7.png)

**Comment by Serabe** [comment]
Closing as duplicate. Thank you!
