### ISSUE TITLE
Cannot able to exclude bower_components folder from ember build and thus ember build fails

### ISSUE THREAD

**Issue by gokatz** [emberjs/ember.js#15137]
I'm using ember via npm `(ember-source)` and I dont need `bower_components` folder at all. So I deleted the folder. Cannot able to exclude `bower_components` folder from `ember build` and thus ember build fails:

```
The Broccoli Plugin: [Funnel: Funnel (bower)] failed with:
Error: Attempting to watch missing directory: bower_components
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/gokul-3858/Home/myapp/jsapps/node_modules/ember-cli-broccoli-sane-watcher/index.js:147:11)
    at /Users/gokul-3858/Home/myapp/jsapps/node_modules/broccoli-builder/lib/builder.js:132:35
    at tryCatch (/Users/gokul-3858/Home/myapp/jsapps/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/gokul-3858/Home/myapp/jsapps/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/gokul-3858/Home/myapp/jsapps/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/gokul-3858/Home/myapp/jsapps/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

tried removing the directory from bowerrc. But no luck :( Any idea

**Comment by locks** [comment]
Are you sure you're not using an addon that relies on a bower package? I cannot reproduce in a v2.12.0 project.

**Comment by gokatz** [comment]
:no_mouth: I haven't updated my CLI. Updated to CLI 2.12.1 and works fine... Thanks @locks 
Closing the issue

**Comment by locks** [comment]
Yay :D Glad you sorted it out!
