### ISSUE TITLE
Updated to Ember 2.13+ and got this error

### ISSUE THREAD

**Issue by robclancy** [emberjs/ember.js#15740]
Not 100% sure if this is the right place to report this. Also happens in ember 2.17.0-beta.1

I am upgrading one version at a time from 2.12. I had an issue with a bad template. The issue here is the error gave absolutely no indication of what was wrong. I found it by deleting one template after another until the error went away. Then I spotted this...

`disabled={{true}}` on a button.

Here is the error I got:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (preprocessedApp & templates)] failed with:
TypeError: Cannot read property 'length' of undefined
    at Object._isMulipartPath (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14898:24)
    at Object._isInlineInvocation (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14901:16)
    at MustacheStatement (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14924:21)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2404:36)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/home/robbo/projects/postedin/marketplace/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp._mergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1815:12)
    at EmberApp.appAndDependencies (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1111:51)
    at EmberApp.javascript (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1235:30)
    at EmberApp.toArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1672:12)
    at EmberApp.toTree (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1694:38)
    at module.exports (/home/robbo/projects/postedin/marketplace/ember-cli-build.js:116:14)
```

**Comment by rwjblue** [comment]
The issue is in https://github.com/emberjs/ember.js/blob/74bda32298d48f183592b6224fd8a86ca472e4c3/packages/ember-template-compiler/lib/plugins/transform-dot-component-invocation.js#L62 we essentially expect it to be a PathExpression but is something else (like a LiteralExpression). A guard would probably be fine here.

**Comment by HeroicEric** [comment]
I believe this is the same bug as https://github.com/emberjs/ember.js/issues/15217

**Comment by rwjblue** [comment]
Thanks @HeroicEric!
