### ISSUE TITLE
yarn test fails with '/' in branch name.

### ISSUE THREAD

**Issue by Parrryy** [emberjs/ember.js#16198]
When running `yarn test` with a '/' in the branch name the test fails with the following message.

```
Test failed: ember-metal/core/main: Ember.VERSION is in alignment with SemVer v2.0.0
    Failed assertion: Ember.VERSION (3.1.0-fix/ember-glimmer-views-doc-update+ca894ce2)is valid SemVer v2.0.0, expected: true, but was: false
    at Object.<anonymous> (http://localhost:13141/ember-tests.js:42211:12)
    at runTest (http://localhost:13141/qunit/qunit.js:1478:30)
    at Test.run (http://localhost:13141/qunit/qunit.js:1464:6)
    at http://localhost:13141/qunit/qunit.js:1670:12
    at Object.advance (http://localhost:13141/qunit/qunit.js:1116:26)
    at begin (http://localhost:13141/qunit/qunit.js:3059:20)
```

It should convert illegal characters in the branch name to something legal.

**Comment by Serabe** [comment]
Closed as the PR is merged.
