### ISSUE TITLE
Tests which pass locally are failing on Heroku

### ISSUE THREAD

**Issue by Charlie-Williams** [emberjs/ember.js#16328]
I am having an issue with Ember/Heroku and I cannot identify exactly where the problems are coming from.

Specifically, the qunit tests are breaking for many routes which use a mixin to send data to Adobe Analytics. The behaviour is exactly as expected but when I was running the tests I got `ReferenceError: dataTracker is not defined`, where `dataTracker` comes from a JS library and significant numbers of tests failing.

Locally, I can solve the issue by wrapping the section of code which calls `dataTracker` in:
```
if (!testing) {
...
}
```
So now the Mixin looks like this:
```
/* global dataTracker */
import Mixin from '@ember/object/mixin';
import Ember from 'ember';

const { testing } = Ember;

export default Mixin.create({
 notifyAdobeAnalytics() {
  if(!testing) {
   let payload = someJSON
	
   dataTracker.trackEvent('newPage', payload);
   }
  }
});
```

This fixes the (many!) broken tests and the behaviour is unaffected... Perfect!

However, when running the same tests in the Heroku staging environment, the same error message is thrown as I was previously getting locally, before adding the `if(!testing)`.

Elsewhere I have looked in our codebase, using the `testing` constant is working normally with Heroku elsewhere so I am unsure as to why it is breaking here. I cannot find any reason why on Heroku I am getting the same error as has been fixed locally.

All error logs are of the structure:
```
ReferenceError: dataTracker is not defined
    at Class.notifyAdobeAnalytics (http://localhost:4200/assets/hivebench-frontend/mixins/adobe-analytics.js:50:1)
    at Class.didTransition (http://localhost:4200/assets/hivebench-frontend/mixins/adobe-analytics.js:24:1)
    at Router$1.triggerEvent (http://localhost:4200/assets/ember-routing/system/router.js:1023:1)
    at trigger (http://localhost:4200/assets/router.js:111:1)
    at finalizeTransition (http://localhost:4200/assets/router.js:2018:1)
    at http://localhost:4200/assets/router.js:1402:1
    at tryCatcher (http://localhost:4200/assets/rsvp.js:215:1)
    at invokeCallback (http://localhost:4200/assets/rsvp.js:393:1)
    at publish (http://localhost:4200/assets/rsvp.js:379:1)
    at http://localhost:4200/assets/ember-testing/ext/rsvp.js:14:1
```

I have tried adding it as a global variable by putting `/* global dataTracker */` at the top of the page and various other things but nothing has worked so far.

The only issues I can find which look  _vaguely_ related are these:
https://github.com/emberjs/ember-qunit/issues/297#issuecomment-352385666
https://github.com/emberjs/ember.js/issues/16006
But they do not have the same problem as I am having.

I am using Ember version 2.16.2 and ember-cli-qunit version 4.0.1

To reiterate,  everything is working exactly as desired, it is only when running the tests in staging that I came across this problem. Is this a known issue or something someone else has been having? Or am I just looking in the wrong places for a solution?

Thanks for your time! Apologies if the explanation is a bit garbled, let me know if anything is unclear.

**Comment by Charlie-Williams** [comment]
Fixed by importing ENV with `import ENV from '../config/environment';` and then wrapping instead with: 
```
if (ENV.environment !== 'test')
```
