### ISSUE TITLE
Tutorial: Tests Fail With 404 on /api/rentals after Ember Data step

### ISSUE THREAD

**Issue by rayascott** [emberjs/ember.js#16368]
I've been following the official Ember tutorial and have been writing the recommended tests along with the app code. After completing the [Ember Data step](https://guides.emberjs.com/v3.0.0/tutorial/ember-data/) I noticed that all of my acceptance tests were failing with a 404 on the GET request to /api/rentals. I am not seeing this issue with the app code however. The rentals display correctly on the rentals page.

Can anyone with some Ember experience shed some light on what's wrong and/or how to fix it? Thanks.

> Promise rejected during "should show rentals as the home page": Ember Data Request GET /api/rentals returned a 404
Payload (Empty Content-Type)
Not found: /api/rentals@ 381 ms
Source: 	
Error: Ember Data Request GET /api/rentals returned a 404
Payload (Empty Content-Type)
Not found: /api/rentals
    at ErrorClass.EmberError (http://localhost:7357/assets/vendor.js:24125:25)
    at ErrorClass.AdapterError (http://localhost:7357/assets/vendor.js:157167:15)
    at new ErrorClass (http://localhost:7357/assets/vendor.js:157185:22)
    at Class.handleResponse (http://localhost:7357/assets/vendor.js:169227:18)
    at ajaxError (http://localhost:7357/assets/vendor.js:169720:25)
    at Class.hash.error (http://localhost:7357/assets/vendor.js:169308:23)
    at fire (http://localhost:7357/assets/vendor.js:3607:31)
    at Object.fireWith [as rejectWith] (http://localhost:7357/assets/vendor.js:3737:7)
    at done (http://localhost:7357/assets/vendor.js:9646:14)
    at XMLHttpRequest.<anonymous> (http://localhost:7357/assets/vendor.js:9887:9)

**Comment by acorncom** [comment]
@rayascott Moving this one as well
