### ISSUE TITLE
dot notation vs Ember.get behavior shift in Ember 3.2 from Ember 3.1.1

### ISSUE THREAD

**Issue by runspired** [emberjs/ember.js#16598]
This issue manifests in Ember 3.2 but not Ember 3.1.1

Imagine you have an instance of an `Ember.Object` (maybe a `service`), and on this instance you have an instance of another `Ember.Object` (perhaps a `model`), and this model has a property. 

If `model` is `isDestroyed: true`, then the following occurs regardless of the value of property (e.g. it could be a computed, an ES getter, a simple boolean), the following behavior divergence below is observed.

```
service.get('model.prop'); // undefined
service.model.prop; // a value
```

Additionally, if `prop` has dependent keys, then the first call will error that you cannot set dependent keys, while subsequent calls will work.
```
service.model.prop; // throws error
service.model.prop; // a value
```

**Comment by runspired** [comment]
cc @Exelord

**Comment by rwjblue** [comment]
Can you share the stack trace?

**Comment by Exelord** [comment]
Stack trace:
Repo: https://github.com/Exelord/ember-custom-actions
Failing CI: https://travis-ci.org/Exelord/ember-custom-actions/jobs/373536919

```
Error: Assertion Failed: Cannot modify dependent keys for `isDeleted` on `<dummy@model:post::ember311:null>` after it has been destroyed.
    at new EmberError (http://localhost:7357/assets/vendor.js:25342:25)
    at Object.assert (http://localhost:7357/assets/vendor.js:24893:15)
    at Meta.writeDeps (http://localhost:7357/assets/vendor.js:36794:54)
    at addDependentKeys (http://localhost:7357/assets/vendor.js:37896:12)
    at ComputedProperty.get (http://localhost:7357/assets/vendor.js:38252:7)
    at Class.CPGETTER_FUNCTION [as isDeleted] (http://localhost:7357/assets/vendor.js:35607:27)
    at eval (eval at <anonymous> (http://localhost:7357/assets/vendor.js:82908:7), <anonymous>:1:12)
    at Class.<anonymous> (http://localhost:7357/assets/vendor.js:82908:7)
    at ComputedProperty.get (http://localhost:7357/assets/vendor.js:38234:30)
    at get (http://localhost:7357/assets/vendor.js:37618:27)"
```

**Comment by Exelord** [comment]
It's still valid case :/

**Comment by pixelhandler** [comment]
Looks like next step is to create a failing test for this scenario

**Comment by locks** [comment]
Is there a status update on this issue?

**Comment by rwjblue** [comment]
Parts of it are definitely still valid, though I don't know that we are likely to change much fundamentally here.

I suspect the underlying issue is that once destroyed we won't actually compute computeds, we will _generally_ only return a previously cached value (if it had been retrieved before).

**Comment by locks** [comment]
Closing as stale. Thanks for reporting and providing the stack trace!
