### ISSUE TITLE
[Bug] Proxied Object observers

### ISSUE THREAD

**Issue by JordanMcDonough** [emberjs/ember.js#17187]
When observing a Proxy Object, the application (sometimes) throws the below assertion:

```
Cannot create a new chain watcher for `[OBJECT IN QUESTION]` after it has been destroyed.
```

I believed this is due to the Proxy object trying to add the observer whilst the content is being/has been destroyed. I was able to solve it by Reopening the ObjectProxy object in an initializer and modifying the willWatchProperty method as below:

_(I know this probably isn't the best fix and instead should be done somewhere in the addObserver function, but this was a simple quick solution for anyone in the meantime)_

```
import {
  get
} from '@ember/object';
import ObjectProxy from '@ember/object/proxy';

export function initialize(applicationInstance) {
  ObjectProxy.reopen({
    willWatchProperty(key) {
      if (this.isDestroying || this.isDestroyed || (this.content != null && (this.content.isDestroying || this.content.isDestroyed))) {
        return;
      }

      return this._super(...arguments);
    },
  });
}

export default {
  initialize
};
```

I don't really know how to reproduce a fiddle for this so if anyone could help that would be appreciated...

Version information:
```
Ember             : 3.5.1
Ember Data        : 3.4.4
```

Error Output:
```
Error: Assertion Failed: Cannot create a new chain watcher for `<staffyourself@model:authenticated-user::ember576:4562>` after it has been destroyed.
    at new EmberError (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\@ember\error\index.js:37:1)
    at assert (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\@ember\debug\index.js:125:1)
    at Meta.writableChainWatchers (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-meta\lib\meta.js:247:1)
    at addChainWatcher (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1718:1)
    at new ChainNode (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1781:1)
    at ChainNode.chain (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1841:1)
    at ChainNode.chain (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1846:1)
    at ChainNode.add (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1819:1)
    at watchPath (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1947:1)
    at watch (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1982:1)
    at addObserver (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1497:1)
    at Proxy.willWatchProperty (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\mixins\-proxy.js:64:1)
    at Proxy.willWatchProperty (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\staffyourself\initializers\flash-messages.js:25:1)
    at Proxy.superWrapper (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-utils.js:308:1)
    at watchKey (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:917:1)
    at addChainWatcher (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1719:1)
    at new ChainNode (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1781:1)
    at ChainNode.chain (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1841:1)
    at ChainNode.chain (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1846:1)
    at ChainNode.add (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1819:1)
    at ChainNode.copyTo (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1809:1)
    at Meta.writableChains (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-meta\lib\meta.js:270:1)
    at finishChains (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-metal.js:1937:1)
    at Class.CoreObject (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\core_object.js:148:1)
    at Class.EmberObject (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\object.js:28:1)
    at Class (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\core_object.js:207:1)
    at Class (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\core_object.js:207:1)
    at new Class (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\core_object.js:207:1)
    at Function.create (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\system\core_object.js:220:1)
    at FactoryManager.create (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:432:1)
    at instantiateFactory (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:277:1)
    at _lookup (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:224:1)
    at processInjections (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:306:1)
    at buildInjections (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:319:1)
    at injectionsFor (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:334:1)
    at FactoryManager.create (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:387:1)
    at instantiateFactory (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:277:1)
    at _lookup (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:224:1)
    at Container.lookup (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\container.js:123:1)
    at Class.lookup (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-runtime\lib\mixins\container_proxy.js:23:1)
    at UnresolvedHandlerInfoByParam.getHandler (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-routing\lib\system\router.js:418:1)
    at UnresolvedHandlerInfoByParam.fetchHandler (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:575:1)
    at UnresolvedHandlerInfoByParam.get (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:734:1)
    at URLTransitionIntent.applyToState (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:1160:1)
    at Router.getTransitionByIntent (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:1473:1)
    at Router.transitionByIntent (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:1280:1)
    at doTransition (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:1908:1)
    at Router.handleURL (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\router.js:1311:1)
    at Class._doURLTransition (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-routing\lib\system\router.js:258:1)
    at Class.handleURL (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-routing\lib\system\router.js:255:1)
    at Class.visit (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\@ember\application\instance.js:189:1)
    at buildAppInstance.then.then (C:\Projects\Work\StaffYourself-WebApp\node_modules\fastboot\src\ember-app.js:260:28)
    at tryCatcher (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\rsvp.js:200:1)
    at invokeCallback (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\rsvp.js:372:1)
    at publish (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\rsvp.js:358:1)
    at C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\ember-testing\lib\ext\rsvp.js:14:1
    at invokeWithOnError (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\backburner.js:283:1)
    at Queue.flush (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\backburner.js:186:1)
    at DeferredActionQueues.flush (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\backburner.js:353:1)
    at Backburner._end (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\backburner.js:808:1)
    at Backburner._boundAutorunEnd (C:\Users\Jordan\AppData\Local\Temp\broccoli-103112Os7Bva8u0zVe\out-807-broccoli_merge_trees\assets\backburner.js:528:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#16541 Not sure if related but seems like a different issue

P.S: I tried to update to master on ember data, and was still able to reproduce the issue, however it broke a plugin inside my project so multiple things broke as well as the current issue and I was unable to try, test and fix on the latest ember (sorry)...

Also, Sorry if I did this wrong I have never posted an issue before, but I read the guidelines so I hope I'm right.

**Comment by pixelhandler** [comment]
@JordanMcDonough thanks for explaining the issue you found and your work around. Yeah it helps to isolate the issue with an example reproduction, if not in an ember-twiddle can use a public repository.

**Comment by BryanCrotaz** [comment]
I had the same issue, and the workaround fixed it for me.

**Comment by locks** [comment]
Closing as the workaround provided addresses the problem and post-Octane there is less of a focus on proxy objects and observers. Thanks for the great report!
