### ISSUE TITLE
Mandatory setter failing with Assertion Failed: You must use set() to set the `connections` property of route

### ISSUE THREAD

**Issue by sumeetattree** [emberjs/ember.js#17203]
`Ember version: 3.4.5`

Here's the error description:
```
Error while processing route:
Error: Assertion Failed: You must use set() to set the `connections` property (of <client@route:index::ember990>) to ``.
    at new EmberError (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:18237:31)
    at assert (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:17099:23)
    at Class.SETTER_FUNCTION [as connections] (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:44153:56)
    at Class.teardownViews (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:50534:26)
    at Class.exit (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:49708:12)
    at callHook (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:62072:38)
    at setupContexts (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:63465:7)
    at finalizeTransition (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:63699:7)
    at http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:63386:14
    at tryCatcher (http://192.168.0.244:4200/assets/vendor-a07ac679768f64e7062b3f17207b642b.js:64099:21)
```
The error seems to be occuring on this [line](https://github.com/emberjs/ember.js/blob/d277c93bc0d357ff50e2c62ec1853794a9b82dd1/packages/ember-routing/lib/system/route.js#L2251)

```js
  teardownViews() {
    if (this.connections && this.connections.length > 0) {
      this.connections = [];    // this right here officer
      once(this._router, '_setOutlets');
    }
  },
```
These same lines are present on the master branch as well. Any pointers? Am I doing something wrong?

**Comment by sumeetattree** [comment]
I just double and triple checked if I am observing the `connections` property anywhere. I couldn't find any references. Is it possible that an addon may be using it? Any idea what kind of addon might be using this `connections` property? Am I missing something very obvious here?

**Comment by rwjblue** [comment]
Glad you got it working, thanks for documenting the fix @sumeetattree!
