### ISSUE TITLE
CI failing after browser tests switched from Edge 17->Edge 18

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#17250]
CI is failing after Browserstack updated from Edge 17 -> 18 

Builds on master with identical code:
Clean: https://travis-ci.org/emberjs/ember.js/jobs/462539239 
Fails: https://travis-ci.org/emberjs/ember.js/jobs/463522769)

Beta is also failing https://travis-ci.org/emberjs/ember.js/jobs/462995715

**Comment by kategengler** [comment]
The test in question is: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/metal/tests/descriptor_test.js#L176

Which has an `isEdge` conditional and a link to https://github.com/emberjs/ember.js/pull/16741#issuecomment-420963181

**Comment by rwjblue** [comment]
```
not ok 10 Edge 18.17763 - @ember/-internals/metal/descriptor: using defineProperty on an object directly:  defining a non-configurable property
    ---
        actual: >
            null
        stack: >
            TypeError: Calling delete on 'foo' is not allowed in strict mode
               at prototype[@test defining a non-configurable property] (http://127.0.0.1:7774/893/dist/ember-tests.js:35149:11)
               at Anonymous function (http://127.0.0.1:7774/893/dist/ember-tests.js:76517:11)
               at runTest (http://127.0.0.1:7774/893/dist/qunit/qunit.js:1478:6)
               at run (http://127.0.0.1:7774/893/dist/qunit/qunit.js:1464:6)
               at Anonymous function (http://127.0.0.1:7774/893/dist/qunit/qunit.js:1670:7)
               at advance (http://127.0.0.1:7774/893/dist/qunit/qunit.js:1116:6)
        message: >
            Died on test #3    at generateTest (http://127.0.0.1:7774/893/dist/ember-tests.js:76516:9)
               at Set.prototype.forEach (native code)
               at moduleFor (http://127.0.0.1:7774/893/dist/ember-tests.js:76500:5)
               at Anonymous function (http://127.0.0.1:7774/893/dist/ember-tests.js:35116:6)
               at Array.prototype.forEach (native code)
               at Anonymous function (http://127.0.0.1:7774/893/dist/ember-tests.js:35115:3)
               at internalRequire (http://127.0.0.1:7774/893/dist/ember.debug.js:62:5): Calling delete on 'foo' is not allowed in strict mode
        Log: |
    ...
```
