### ISSUE TITLE
SIGSEGV in `ember build -prod`

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#17832]
This started happening in CI on master recently. It may be related to babel? It _seems_ to only happen in the node tests only.

```
Build Error (broccoli-persistent-filter:Babel) in @ember/-internals/container/tests/registry_test.js
Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
=================================================================================
ENV Summary:
  TIME: Mon Apr 01 2019 19:58:16 GMT+0000 (UTC)
  TITLE: ember
  ARGV:
  - /home/travis/.nvm/versions/node/v6.17.0/bin/node
  - /home/travis/build/emberjs/ember.js/node_modules/.bin/ember
  - build
  - -prod
  EXEC_PATH: /home/travis/.nvm/versions/node/v6.17.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1554148597544-0.38615130618596694
  - /home/travis/build/emberjs/ember.js/node_modules/.bin
  - /home/travis/.config/yarn/link/node_modules/.bin
  - /home/travis/.nvm/versions/node/v6.17.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/travis/.nvm/versions/node/v6.17.0/lib/node_modules/npm/bin/node-gyp-bin
  - /home/travis/.nvm/versions/node/v6.17.0/bin/node_modules/npm/bin/node-gyp-bin
  - /home/travis/.yarn/bin
  - /home/travis/.rvm/gems/ruby-2.4.1/bin
  - /home/travis/.rvm/gems/ruby-2.4.1@global/bin
  - /home/travis/.rvm/rubies/ruby-2.4.1/bin
  - /home/travis/.rvm/bin
  - ./node_modules/.bin
  - /home/travis/firefox-latest/firefox
  - /home/travis/bin
  - /home/travis/.local/bin
  - /opt/pyenv/shims
  - /home/travis/.phpenv/shims
  - /home/travis/perl5/perlbrew/bin
  - /home/travis/.nvm/versions/node/v6.17.0/bin
  - /home/travis/.kiex/elixirs/elixir-1.4.5/bin
  - /home/travis/.kiex/bin
  - /home/travis/gopath/bin
  - /home/travis/.gimme/versions/go1.7.4.linux.amd64/bin
  - /usr/local/phantomjs/bin
  - /usr/local/phantomjs
  - /usr/local/neo4j-3.2.7/bin
  - /usr/local/maven-3.5.2/bin
  - /usr/local/cmake-3.9.2/bin
  - /usr/local/clang-5.0.0/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /home/travis/.phpenv/bin
  - /opt/pyenv/bin
  - /home/travis/.yarn/bin
  PLATFORM: linux x64
  FREEMEM: 1856606208
  TOTALMEM: 7843196928
  UPTIME: 255
  LOADAVG: 1.1865234375,0.74609375,0.3193359375
  CPUS:
  - Intel(R) Xeon(R) CPU @ 2.30GHz - 2300
  - Intel(R) Xeon(R) CPU @ 2.30GHz - 2300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.8.0
  - icu: 58.2
  - modules: 48
  - napi: 3
  - node: 6.17.0
  - openssl: 1.0.2r
  - uv: 1.16.1
  - v8: 5.1.281.111
  - zlib: 1.2.11
ERROR Summary:
  - broccoliBuilderErrorStack: Error: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
    at ChildProcess.<anonymous> (/home/travis/build/emberjs/ember.js/node_modules/workerpool/lib/WorkerHandler.js:260:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
  - code: [undefined]
  - codeFrame: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
  - errorMessage: @ember/-internals/container/tests/registry_test.js: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
        in /tmp/broccoli-5493TCY0zxs4nm58/out-070-broccoli_merge_trees
        at broccoli-persistent-filter:Babel
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @ember/-internals/container/tests/registry_test.js
    - line: [undefined]
    - treeDir: /tmp/broccoli-5493TCY0zxs4nm58/out-070-broccoli_merge_trees
  - message: @ember/-internals/container/tests/registry_test.js: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
        in /tmp/broccoli-5493TCY0zxs4nm58/out-070-broccoli_merge_trees
        at broccoli-persistent-filter:Babel
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:Babel
  - originalErrorMessage: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
  - stack: Error: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGSEGV`
    workerpool.script: `/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnArgs: `/home/travis/.nvm/versions/node/v6.17.0/bin/node,/home/travis/build/emberjs/ember.js/node_modules/broccoli-babel-transpiler/lib/worker.js`
    spawnfile: `/home/travis/.nvm/versions/node/v6.17.0/bin/node`
    stdout: `null`
    stderr: `null`
    at ChildProcess.<anonymous> (/home/travis/build/emberjs/ember.js/node_modules/workerpool/lib/WorkerHandler.js:260:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
=================================================================================
error Command failed with exit code 1.
```

There are two general problems:

1. Why are we getting SIGSEGV? How do we fix it?
2. Why do we keep running `yarn test:node` anyway, even when the build failed? (All the tests basically fail with something like `Cannot find module '/home/travis/build/emberjs/ember.js/dist/ember.debug'`.)

**Comment by brondsem** [comment]
We ran into this recently and the problem was dozens of broccoli-babel-transpiler worker processes being spawned and running out of memory.  Setting `JOBS=2` or something like that can fix it.

https://github.com/emberjs/ember.js/issues/15641 has a lot of additional info

**Comment by locks** [comment]
Closing as no longer relevant.
