### ISSUE TITLE
[BETA] Nested co-location doesn't seem to work

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18255]
# Setup

```
/tmp ❯❯❯ ember new --yarn test-nested-co-location                                                                                                   ✘ 127
installing app
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/optional-features.json
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.js
  create tests/helpers/.gitkeep
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Yarn: Installed dependencies
Successfully initialized git.
/tmp ❯❯❯ cd test-nested-co-location
/t/test-nested-co-location ❯❯❯ yarn add ember-source@~3.13.0-beta.1                                                                           ✘ 130 master
yarn add v1.15.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "ember-cli-app-version > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-plugin-node@9.1.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@1.4.0" has unmet peer dependency "eslint@>=4.19.1".
[5/5] 🔨  Building fresh packages...

success Saved lockfile.
warning "ember-source" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
success Saved 1 new dependency.
info Direct dependencies
└─ ember-source@3.13.0-beta.1
info All dependencies
└─ ember-source@3.13.0-beta.1
✨  Done in 5.66s.
❯❯❯ yarn add "ember-cli/ember-cli-htmlbars#colocation"                                                           ✘ 1 master ✱ ◼
yarn add v1.15.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "ember-cli-app-version > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-plugin-node@9.1.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@1.4.0" has unmet peer dependency "eslint@>=4.19.1".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
warning "ember-cli-htmlbars" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
success Saved 1 new dependency.
info Direct dependencies
└─ ember-cli-htmlbars@3.1.0
info All dependencies
└─ ember-cli-htmlbars@3.1.0
✨  Done in 4.99s.
/t/test-nested-co-location ❯❯❯ yarn test                                                                                                          master ✱
yarn run v1.15.2
$ ember test
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Environment: test
cleaning up...
Built project successfully. Stored in "/private/tmp/test-nested-co-location/tmp/class-tests_dist-PwaiqWCy.tmp".
ok 1 Chrome 76.0 - [4 ms] - ESLint | app: app.js
ok 2 Chrome 76.0 - [1 ms] - ESLint | app: resolver.js
ok 3 Chrome 76.0 - [0 ms] - ESLint | app: router.js
ok 4 Chrome 76.0 - [0 ms] - TemplateLint: test-nested-co-location/templates/application.hbs
ok 5 Chrome 76.0 - [0 ms] - ESLint | tests: test-helper.js
ok 6 Chrome 76.0 - [1 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..6
# tests 6
# pass  6
# skip  0
# fail  0

# ok
✨  Done in 13.20s.
```

# Test

```
/t/test-nested-co-location ❯❯❯ yarn ember generate component --component-structure=nested foo                                                 ✘ 1 master ✱
yarn run v1.15.2
$ /private/tmp/test-nested-co-location/node_modules/.bin/ember generate component --component-structure=nested foo
installing component
  create app/components/foo/index.js
  create app/components/foo/index.hbs
installing component-test
  create tests/integration/components/foo-test.js
✨  Done in 1.38s.
/t/test-nested-co-location ❯❯❯ yarn test                                                                                                        master ✱ ◼
yarn run v1.15.2
$ ember test
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Environment: test
cleaning up...
Built project successfully. Stored in "/private/tmp/test-nested-co-location/tmp/class-tests_dist-S6J5tBOo.tmp".
not ok 1 Chrome 76.0 - [99 ms] - Integration | Component | foo: it renders
    ---
        actual: >
            [object Object]
        stack: >
            Error: Compile Error: Cannot find component foo
                at http://localhost:7357/assets/vendor.js:55363:15
                at Compilers.compile (http://localhost:7357/assets/vendor.js:55255:7)
                at compile (http://localhost:7357/assets/vendor.js:55948:17)
                at LazyCompiler.add (http://localhost:7357/assets/vendor.js:56142:14)
                at CompilableProgram.compile (http://localhost:7357/assets/vendor.js:55906:44)
                at OutletComponentManager.getLayout (http://localhost:7357/assets/vendor.js:18259:24)
                at Object.evaluate (http://localhost:7357/assets/vendor.js:60910:24)
                at AppendOpcodes.evaluate (http://localhost:7357/assets/vendor.js:59299:19)
                at LowLevelVM.evaluateSyscall (http://localhost:7357/assets/vendor.js:62512:22)
                at LowLevelVM.evaluateInner (http://localhost:7357/assets/vendor.js:62458:14)
        message: >
            Compile Error: Cannot find component foo
        negative: >
            false
        browser log: |
    ...
ok 2 Chrome 76.0 - [0 ms] - ESLint | app: app.js
ok 3 Chrome 76.0 - [0 ms] - ESLint | app: components/foo/index.js
ok 4 Chrome 76.0 - [0 ms] - ESLint | app: resolver.js
ok 5 Chrome 76.0 - [0 ms] - ESLint | app: router.js
ok 6 Chrome 76.0 - [0 ms] - TemplateLint: test-nested-co-location/templates/application.hbs
ok 7 Chrome 76.0 - [0 ms] - ESLint | tests: integration/components/foo-test.js
ok 8 Chrome 76.0 - [0 ms] - ESLint | tests: test-helper.js
ok 9 Chrome 76.0 - [0 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..9
# tests 9
# pass  8
# skip  0
# fail  1
Testem finished with non-zero exit code. Tests failed.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not 100% sure if we intended to make this work of if the build tools are supposed to normalize it.

**Comment by chancancode** [comment]
@rwjblue thoughts?

**Comment by chancancode** [comment]
Moved to 3.14 milestone since this feature is gated on the octane flag

**Comment by mydea** [comment]
Not sure if this is directly related, but co-location in nested folders is generally working fine for me, except for one case:

I just tried moving an (internal) addon to use co-location, and it does not work if I have a folder structure like this (omitting all .js files for the components, for simplicity)

- addon
  - components
    - my-component
       - sub-a.hbs
       - sub-b.hbs
    - my-component.hbs
- app
  - components
    - my-component
       - sub-a.js
       - sub-b.js
    - my-component.js

Where the `app/components/my-component.js` re-export looks like this:

```js
export {
  default
} from 'my-addon/components/my-component';
```

It will not find this component in the app.
It works if I move that filet to `app/components/my-component/index.js` instead.

**Comment by rwjblue** [comment]
@mydea - Thank you for reporting! Would you mind opening an issue over on ember-cli-htmlbars for this (also a small repro would be wonderful, if you have the time)?

**Comment by btecu** [comment]
Looks like https://github.com/ember-cli/ember-cli-htmlbars/issues/330 was closed. Can this be closed too?

**Comment by rwjblue** [comment]
Ya, thank you @btecu!
