### ISSUE TITLE
Classic template import like "import template from 'some-path/to/template'" not working for Glimmer component

### ISSUE THREAD

**Issue by morizmatik** [emberjs/ember.js#18361]
> **Ember** | 3.10.2
> **repository**: https://github.com/morizmatik/glimmer-classic-template-import

When I try use it:
```
import Component from "@glimmer/component";
import layout from "../templates/components/leasing-file-upload-button";
import { setComponentTemplate } from "@ember/component";

class UploadButton extends Component {
  test = "TEST";
}

export default setComponentTemplate(layout, UploadButton);
```
I get this error:
```
Build Error (broccoli-persistent-filter:Babel > [Babel: leasing-file-upload-button]) in leasing-file-upload-button/components/leasing-file-upload-button.js

/home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {


Stack Trace and Error Report: /tmp/error.dump.fd33ed9f624f0e4f409d54bbb73ea259.log
```

Here is **/tmp/error.dump.fd33ed9f624f0e4f409d54bbb73ea259.log**:
```
=================================================================================

ENV Summary:

  TIME: Fri Sep 06 2019 09:48:03 GMT+0200 (GMT+02:00)
  TITLE: ember
  ARGV:
  - /home/bslam/.nvm/versions/node/v10.15.3/bin/node
  - /home/bslam/.nvm/versions/node/v10.15.3/bin/ember
  - s
  EXEC_PATH: /home/bslam/.nvm/versions/node/v10.15.3/bin/node
  TMPDIR: /tmp
  SHELL: /bin/zsh
  PATH:
  - /usr/local/lib/nodejs/node-v10.15.0-linux-x64/bin
  - /home/bslam/bin
  - /home/bslam/.local/bin
  - /home/bslam/.nvm/versions/node/v10.15.3/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 179204096
  TOTALMEM: 16690667520
  UPTIME: 147185
  LOADAVG: 3.97998046875,2.986328125,3.0693359375
  CPUS:
  - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz - 3410
  - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz - 3397
  - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz - 3431
  - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz - 3401
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.3
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.51
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
    at File.buildCodeFrameError (/home/bslam/Documents/beatstore/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at ImportDeclaration.specifiers.forEach.specifierPath (/home/bslam/Documents/beatstore/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:116:26)
    at Array.forEach (<anonymous>)
    at PluginPass.ImportDeclaration (/home/bslam/Documents/beatstore/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:78:22)
    at newFn (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/context.js:118:16)
  - code: [undefined]
  - codeFrame: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
  - errorMessage: leasing-file-upload-button/components/leasing-file-upload-button.js: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
        in /tmp/broccoli-21098HTZqyw077HiT/out-357-funnel_funnel_addon_js
        at broccoli-persistent-filter:Babel > [Babel: leasing-file-upload-button] (Babel: leasing-file-upload-button)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: leasing-file-upload-button/components/leasing-file-upload-button.js
    - line: [undefined]
    - treeDir: /tmp/broccoli-21098HTZqyw077HiT/out-357-funnel_funnel_addon_js
  - message: leasing-file-upload-button/components/leasing-file-upload-button.js: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
        in /tmp/broccoli-21098HTZqyw077HiT/out-357-funnel_funnel_addon_js
        at broccoli-persistent-filter:Babel > [Babel: leasing-file-upload-button] (Babel: leasing-file-upload-button)
  - name: BuildError
  - nodeAnnotation: Babel: leasing-file-upload-button
  - nodeName: broccoli-persistent-filter:Babel > [Babel: leasing-file-upload-button]
  - originalErrorMessage: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
  - stack: SyntaxError: /home/bslam/Documents/beatstore/leasing-file-upload-button/components/leasing-file-upload-button.js: @ember/component does not have a setComponentTemplate export
   6 | import { inject as service } from "@ember/service";
   7 | import { tracked } from "@glimmer/tracking";
>  8 | import { setComponentTemplate } from "@ember/component";
     | ^
   9 | import layout from "../templates/components/leasing-file-upload-button";
  10 | 
  11 | class UploadButton extends Component {
    at File.buildCodeFrameError (/home/bslam/Documents/beatstore/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at ImportDeclaration.specifiers.forEach.specifierPath (/home/bslam/Documents/beatstore/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:116:26)
    at Array.forEach (<anonymous>)
    at PluginPass.ImportDeclaration (/home/bslam/Documents/beatstore/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:78:22)
    at newFn (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/bslam/Documents/beatstore/node_modules/@babel/traverse/lib/context.js:118:16)

=================================================================================

```

**Comment by rwjblue** [comment]
@lifeart - for that you need at least ember-cli-babel@7.11.0

**Comment by rwjblue** [comment]
Also, there is no polyfill for setComponentTemplate yet, it only works on Ember 3.13+ (I noticed at the top you mentioned it was on Ember 3.10).

**Comment by morizmatik** [comment]
@rwjblue Thank you I'll update to 3.13. Today I updated to 3.12)
And I'll add ember-cli-babel@7.11.0

**Comment by morizmatik** [comment]
In Ember 3.13 is working
