### ISSUE TITLE
Unable to run application on 3.14 with ember-engines

### ISSUE THREAD

**Issue by catz** [emberjs/ember.js#18602]
Hello 

This bug is very similar to #17678

```
  - location:
    - file: ember-engines/test-support/engine-resolver-for.js

  - nodeAnnotation: Babel: ember-engines
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-engines]
  - originalErrorMessage: Cannot read property 'getHash' of null
  - stack: TypeError: Cannot read property 'getHash' of null
    at hashForDep (/Users/catz/Projects/some/frontend/node_modules/ember-cli-babel/node_modules/hash-for-dep/index.js:67:24)
    at optionsHash (/Users/catz/Projects/some/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/lib/options-hash.js:58:51)
    at Babel.optionsHash (/Users/catz/Projects/some/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:117:26)
    at Babel.cacheKeyProcessString (/Users/catz/Projects/some/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:124:15)
    at Object.processString (/Users/catz/Projects/some/frontend/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:19)
```

Looks like we need to bump hash-for-dep in broccoli-babel-transpiler
the same was as in https://github.com/broccolijs/broccoli-persistent-filter/commit/357c244574ad4b0f7716bd779c754576b979175c

https://github.com/babel/broccoli-babel-transpiler/pull/176

And then update broccoli-babel-transpiler in ember-cli-babel

FYI

```
  "devDependencies": {
    "@ember-intl/cp-validations": "^4.0.1",
    "@ember/optional-features": "^1.0.0",
    "babel-eslint": "^10.0.3",
    "bootstrap-sass": "^3.3.7",
    "broccoli-asset-rev": "^3.0.0",
    "broccoli-concat": "^4.2.0",
    "broccoli-funnel": "3.0.0",
    "broccoli-merge-trees": "^4.0.0",
    "ember-ajax": "^5.0.0",
    "ember-api-actions": "^0.2.8",
    "ember-auto-import": "^1.5.3",
    "ember-best-language": "^2.0.1",
    "ember-bootstrap": "3.1.0",
    "ember-cached-shoe": "^0.2.1",
    "ember-cli": "~3.14.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.11.1",
    "ember-cli-cjs-transform": "^2.0.0",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-dropzonejs": "1.3.5",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-fastboot": "^2.2.1",
    "ember-cli-flash": "^1.7.2",
    "ember-cli-form-data": "^2.1.1",
    "ember-cli-htmlbars": "^4.0.5",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-inline-content": "^0.4.1",
    "ember-cli-meta-tags": "^5.3.0",
    "ember-cli-mirage": "^1.1.4",
    "ember-cli-moment-shim": "^3.5.0",
    "ember-cli-polyfill-io": "^1.2.3",
    "ember-cli-replace": "^0.7.0",
    "ember-cli-sass": "^10.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.3",
    "ember-cli-uglify": "^3.0.0",
    "ember-cli-update": "^0.43.3",
    "ember-component-attributes": "^0.1.3",
    "ember-component-css": "^0.7.4",
    "ember-component-inbound-actions": "^1.3.0",
    "ember-composable-helpers": "^2.3.1",
    "ember-cookies": "^0.5.2",
    "ember-cp-validations": "^4.0.0-beta.10",
    "ember-data": "~3.14.0",
    "ember-engines": "^0.8.3",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^6.7.1",
    "ember-flatpickr": "2.14.3",
    "ember-font-awesome": "^4.0.0-rc.4",
    "ember-fsm": "^1.1.0",
    "ember-g-recaptcha": "^1.0.0",
    "ember-inflector": "^3.0.1",
    "ember-intl": "^4.2.2",
    "ember-load-initializers": "^2.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^7.4.1",
    "ember-page-title": "^5.1.0",
    "ember-qunit": "^4.5.1",
    "ember-radio-button": "^2.0.1",
    "ember-resolver": "^5.3.0",
    "ember-source": "~3.14.1",
    "ember-truth-helpers": "^2.0.0",
    "ember-useragent": "^0.9.1",
    "ember-welcome-page": "^4.0.0",
    "emberx-select": "^3.1.1",
    "eslint-plugin-ember": "^7.7.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-qunit": "^4.0.0",
    "fastboot-transform": "^0.1.3",
    "glob": "^7.1.6",
    "http-proxy": "^1.18.0",
    "loader.js": "^4.7.0",
    "moment-duration-format": "^2.3.2",
    "morgan": "^1.9.0",
    "qunit-dom": "^0.9.2",
    "sass": "^1.23.7"
  },
```

**Comment by catz** [comment]
removing yarn.lock and running yarn again solved the issue.
