### ISSUE TITLE
`{{#each}}` without any params causes error

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18673]
[This line](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-each-track-array.ts#L36) broke the [inspector's test](https://github.com/emberjs/ember-inspector/runs/384340232):

```
  - broccoliBuilderErrorStack: TypeError: /home/runner/work/ember-inspector/ember-inspector/ember-inspector/tests/ember_debug/view-debug-test.js: Cannot read property 'type' of undefined
    at BlockStatement (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:10590:28)
    at visitNode (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:7537:16)
    at visitArray (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:7628:20)
    at visitKey (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:7605:7)
    at visitNode (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:7559:9)
    at traverse (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:7669:5)
    at preprocess (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:8708:9)
    at precompile (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:4538:38)
    at precompile (/home/runner/work/ember-inspector/ember-inspector/node_modules/ember-source/dist/ember-template-compiler.js:11513:37)
    at compileTemplate (/home/runner/work/ember-inspector/ember-inspector/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
```

This was caused by [this line](https://github.com/emberjs/ember-inspector/blob/14c2d19cfc7e0993f53c33d01ed62391132dc4b1/tests/ember_debug/view-debug-test.js#L150) in the inspector's tests. While it's an invalid usage and you should probably get _some_ error either at runtime or build time, the way it fails now is unexpected.

**Comment by mixonic** [comment]
Dang I just debugged this same thing :sob:

**Comment by chancancode** [comment]
@mixonic sounds correct to me. Feel free to remove it again against master when you get a chance

**Comment by locks** [comment]
Resolved.
