### ISSUE TITLE
Infinite loop on javascript errors with fastboot

### ISSUE THREAD

**Issue by gedaiu** [emberjs/ember.js#18973]
Every time when I have a javascript error in my ember project the server goes into some infinite loop and I have to run a killall -9 ember to stop it. It’s not clear for me if I have a miss configured project or this is common with fastboot.

Does anyone know a fix for this?

Here is some of the stack trace that gets printed:

```
 at Backburner._run (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1009:1)
    at Backburner._join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:989:1)
    at Backburner.join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:760:1)
    at Array.loopEnd (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/@ember/-internals/glimmer/index.js:8888:1)
    at Backburner._trigger (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1084:1)
    at Backburner._end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:979:1)
    at Backburner.end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:710:1)
    at Backburner._run (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1009:1)
    at Backburner._join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:989:1)
    at Backburner.join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:760:1)
    at Array.loopEnd (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/@ember/-internals/glimmer/index.js:8888:1)
    at Backburner._trigger (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1084:1)
    at Backburner._end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:979:1)
    at Backburner.end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:710:1)
    at Backburner._run (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1009:1)
    at Backburner._join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:989:1)
    at Backburner.join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:760:1)
    at Array.loopEnd (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/@ember/-internals/glimmer/index.js:8888:1)
    at Backburner._trigger (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1084:1)
    at Backburner._end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:979:1)
    at Backburner.end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:710:1)
    at Backburner._run (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1009:1)
    at Backburner._join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:989:1)
    at Backburner.join (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:760:1)
    at Array.loopEnd (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/@ember/-internals/glimmer/index.js:8888:1)
    at Backburner._trigger (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:1084:1)
    at Backburner._end (/tmp/broccoli-48570D2fCP9dayOEL/out-592-append_ember_auto_import_analyzer/assets/backburner.js:979:1)
    at Bac
```

**Comment by rwjblue** [comment]
Is this error output in the browser console or in the running `ember s` terminal? We might need to try to isolate this in a demo repo to figure out what combo of packages is the causing things...

**Comment by gedaiu** [comment]
@rwjblue The stack is printed in the terminal. This is happening in my open source project: https://gitlab.com/GISCollective/frontend/web-frontend I am not sure how to isolate it, but I can try if it is needed.

**Comment by rwjblue** [comment]
It is worthwhile to isolate the source (I find that doing that exercise often points out which thing is causing the problem) by porting the minimum set of things into a `ember new my-test-app`, doing so will almost certainly make this easier to solve.

**Comment by james75** [comment]
I am experiencing this same issue it only started to happen after upgrading ember. Where you able to track down the cause?

**Comment by gedaiu** [comment]
Unfortunately not. I gave up after 10 minutes of investigation :)

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
