### ISSUE TITLE
[Bug] Syntax error when running Ember 3.26.1 with Fastboot v2.2.3

### ISSUE THREAD

**Issue by janwerkhoven** [emberjs/ember.js#19550]
### 🐞 Describe the Bug

[Ember Fastboot](https://ember-fastboot.com/) v2.2.3 throws a **syntax error** with Ember v3.26.1, preventing further use of Fastboot.

### 🔬 Minimal Reproduction

```
ember new foo --yarn true
cd foo
ember install ember-cli-fastboot
yarn start
```

Open [http://localhost:4200](http://localhost:4200) and you'll see Fastboot throwing a syntax error. 🔥 

Open [http://localhost:4200/?fastboot=false](http://localhost:4200/?fastboot=false), no issues. 👌🏻 

### 😕 Actual Behavior
We're unable to use Fastboot v2.2.3 with Ember v3.26.1.

### 🤔 Expected Behavior
To be able to use Fastboot v2.2.3 with Ember v3.26.1.

### 🌍 Environment

- Ember: v3.26.1
- Fastboot: v2.2.3
- Node: v12.13.1
- Yarn: v1.22.5
- OS: MacOS Big Sur v11.3
- Browser: Version 90.0.4430.212

### ➕ Additional Context

Github repo: 

https://github.com/janwerkhoven/reproduce-ember-fastboot-syntax-error

The error observed:

```
/var/folders/cy/_q4k3hj55wb8fxb3f1sr6trm0000gn/T/broccoli-28108o91P4NJ9dUNV/out-308-append_ember_auto_import_analyzer/assets/vendor.js:24646
      this.forEach(item => ret.push(item[methodName]?.(...args)));
                                                     ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:84:7)
    at VMSandbox.eval (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/jw/Code/ember-reproduce-error/node_modules/fastboot/src/index.js:52:10)
    at /Users/jw/Code/ember-reproduce-error/node_modules/ember-cli-fastboot/index.js:335:29
```

**Comment by chancancode** [comment]
Optional chaining is available in node 14+ according to MDN. Either upgrade node or add node 12 to your targets.js so it is transpired by Babel at build time.

**Comment by janwerkhoven** [comment]
TIL: optional chaining ❤️ 

```
echo "v14.17.0" > .nvmrc
nvm install
yarn start
```

Fastboot no longer throws syntax error! 🎉 

Thanks @chancancode for quick resolve.

**Comment by chancancode** [comment]
No problem, you may also want to check out [Volta](https://volta.sh) for managing node versions
