### ISSUE TITLE
[Bug] Bug report

### ISSUE THREAD

**Issue by francispeixoto** [emberjs/ember.js#19757]
### 🐞 Describe the Bug
Upgrading ember-quint from 4 to 5 generated this build fail. according to https://github.com/kaliber5/ember-bootstrap/issues/1611 this might be related to code, rather than qunit or ember-boostrap, 

### 🔬 Minimal Reproduction
- Upgraded ember-qunit from 4.6.0 to 5.1.4 and went through migration guide: https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md
- Generate `ember build` on branch following migration steps

### 😕 Actual Behavior

stack trace on build: 

> not ok 1 Chrome 93.0 - [28 ms] - Integration | Component | topnav: it renders
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it renders": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 2 Chrome 93.0 - [15 ms] - Unit | Controller | application: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 3 Chrome 93.0 - [13 ms] - Unit | Route | application: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 4 Chrome 93.0 - [13 ms] - Unit | Route | contact: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 5 Chrome 93.0 - [13 ms] - Unit | Route | index: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...
not ok 6 Chrome 93.0 - [13 ms] - Unit | Route | resume: it exists
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of null (reading 'classList')
                at Class.setup (http://localhost:7357/assets/vendor.js:32658:33)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:34232:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:34156:14)
                at http://localhost:7357/assets/vendor.js:37668:77
                at initializePromise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:172:240)
                at new Promise (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:437:298)
                at Class.boot (http://localhost:7357/assets/vendor.js:37668:27)
                at http://localhost:7357/assets/test-support.js:3826:65
                at tryCatcher (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:793)
                at invokeCallback (webpack://__ember_auto_import__/./node_modules/ember-bootstrap/node_modules/rsvp/dist/rsvp.es.js?:170:3997)
        message: >
            Promise rejected before "it exists": Cannot read properties of null (reading 'classList')
        negative: >
            false
        browser log: |
    ...

### 🤔 Expected Behavior
Successful build using the latest version of ember-qunit

### 🌍 Environment

ember-cli: 3.28.0
node: 14.17.6
os: linux x64

**Comment by jfdnc** [comment]
Without all the context, it seems like that TypeError is likely being thrown [in this assertion after `rootElement.parentNode` is assigned](https://github.com/emberjs/ember.js/blob/a3a299cd66940bdef1531e89b94f120584119ae3/packages/%40ember/-internals/views/lib/system/event_dispatcher.js#L160-L173). If your tests are passing a custom `rootElement`, it seems like that could potentially [evaluate to `null`](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode#notes), which would repro the error you're seeing. I'd start poking around there and see if you can trace back from that point in your testing environment.

It also seems like that assertion could flip around to `while` from `do..while` and have a bit of added safety against the potential `null` value here.

**Comment by brendaHuang-2023** [comment]
I am seeing the same error when upgrading ember-qunit from 4.6.0 to 5.1.5. 

I copied all the dependency versions from ember-new-output for 4.0.1: https://github.com/ember-cli/ember-new-output/blob/v4.0.1/package.json

ember-cli: 4.0.1
node: 16.18.0
os: MacOS Ventura 13

**Comment by brendaHuang-2023** [comment]
@jfdnc The tests were passing prior to upgrading to ember-qunit from 4.6.0 to 5.1.5

**Comment by kategengler** [comment]
I didn't see a corresponding issue on `ember-qunit`. I hope that you were able to get passed this issue.

A guard was added around that code for nulls in https://github.com/emberjs/ember.js/commit/9fb35c41563d450293d991d313bd99f82b4acece
