### ISSUE TITLE
[Bug] ember not generating blueprints on z/OS

### ISSUE THREAD

**Issue by laijonathan** [emberjs/ember.js#20300]
On z/OS, there seems to be an issue where ember generate does not generate the necessary files.

When running the test suite on z/OS:

```
  2) Acceptance: ember generate in-addon-dummy
       dummy blueprint foo:
     Error: ENOENT: no such file or directory, open '/home/jolai/zos_fork/ember-cli/tmp/20221011-6129-psrjd9.p2bb/my-addon/blueprints/foo/index.js'
      at Object.openSync (node:fs:609:3)
      at Object.readFileSync (node:fs:474:35)
      at FileHelper.get (node_modules/chai-files/src/file-helper.js:42:26)
      at Context.<anonymous> (tests/acceptance/addon-dummy-generate-test.js:58:43)

```
I have tried testing this feature with both the CLI and by calling it programmatically. 

The blueprints are created successfully on Linux but on z/OS, nothing is created.

Linux
```
$ ember new my_test
$ cd my_test
$ ember generate blueprint foo --dummy
installing blueprint
	  create blueprints/foo/index.js
$ ls blueprints/foo
index.js
$ 
```

z/OS
```
$ ember new my_test
$ cd my_test
$ ember generate blueprint foo --dummy
installing blueprint
$ ls blueprints/foo
ls: FSUM6785 File or directory "foo" is not found
$
```

Script.js
```
   const ember = require('../helpers/ember');
   let r2 = ember(['generate', 'blueprint', 'foo', '--dummy'])
```

Linux
```
$ node script.js
$ ls blueprints
foo
```

z/OS
```
$ node script.js
$ ls blueprints
ls: FSUM6785 File or directory "blueprints" is not found
```

Could someone point me to the code/components that generates the blueprint files?

Thanks

Output from ember version --verbose && npm --version && yarn --version:
```
ember-cli: 4.8.0
node: 18.9.1
v8: 10.2.154.15-node.12
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 3.0.5+quic
cldr: 41.0
icu: 71.1
tz: 2022b
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: os390 s390x
8.19.1
bash: yarn: command not found
```

**Comment by kategengler** [comment]
Hi! The generate code is in [ember-cli](https://github.com/ember-cli/ember-cli/), while the blueprints are in various projects. We have never tested ember-cli on z/OS. We test on Ubuntu, MacOS and Windows.

**Comment by kategengler** [comment]
I'm going to close this as we do not test on z/OS and do not intend to do so.

**Comment by NullVoxPopuli** [comment]
any browser/environment tho that happens to have equiv % coverage of of the test262 suite, should work tho 

https://test262.fyi/

**Comment by kategengler** [comment]
I don't really know anything about z/OS. While it is Unix based clearly it behaves differently than Linux. Could be the filesystem. Either way, we're not going to be debugging on that OS and we cannot reasonably test against it with the resources we have.

**Comment by NullVoxPopuli** [comment]
Ccc
