### ISSUE TITLE
[Bug] 3.28 - Conditionally rendering a modifier throws error

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#20631]
### 🐞 Describe the Bug

Say we are rendering a template like this:

```handlebars
<button {{(if this.bindClickHandler (modifier this.on "click" this.handleClick))}}>
  Click Me
</button>
```

And a component definition like this:

```handlebars
import Component from '@glimmer/component';
import { on } from '@ember/modifier';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';

export default class UsesOn extends Component {
  @tracked wasClicked = false;
  @tracked bindClickHandler = true;
  on = on;

  @action
  handleClick() {
    this.wasClicked = true;
  }

  @action
  toggleBindClickHandler() {
    this.bindClickHandler = !this.bindClickHandler;
  }
}
```

```
Calling `toggleBindClickHandler` to change the condition in the `if` statement should cleanly apply the `on` modifier. Instead, after `this.bindClickHandler` goes from `true` to `false` to `true` again, on the 3rd change when we go back to truth, we see the following error instead:

Uncaught (in promise) Error: You can only pass two positional arguments (event name and callback) to the `on` modifier, but you provided 4. Consider using the `fn` helper to provide additional arguments to the `on` callback.
    at OnModifierState.updateFromArgs (runtime.js:7277:1)
    at OnModifierManager.install (runtime.js:7486:1)
    at runtime.js:4840:1
    at track (validator.js:820:1)
    at TransactionImpl.commit (runtime.js:4839:1)
    at EnvironmentImpl.commit (runtime.js:4936:1)
    at inTransaction (runtime.js:4961:1)
    at Renderer._renderRoots (index.js:7779:1)
    at Renderer._renderRootsTransaction (index.js:7831:1)
    at Renderer._revalidate (index.js:7873:1)
```

### 🔬 Minimal Reproduction

* Clone this repository https://github.com/fivetanley/local-modifier-reproduction
* `npm I`
* `npm start`
* click the button to toggle the handler
* see that after the 3rd toggle an error appears in the console

### 😕 Actual Behavior

Ember and/or glimmer seems to copy the arguments and append them to the existing arguments. This changes the amount of arguments from 2 to 4 and throws the error mentioned above.

### 🤔 Expected Behavior

The modifier should be able to conditionally removed/enabled without error.

### 🌍 Environment

- Ember: - 3.28.12
- Node.js/npm: - 16/8.19.4
- OS: - Mac OS
- Browser: - Safari/Firefox/Chrome

**Comment by kategengler** [comment]
3.28 is long out of support -- Does this affect any supported versions?

**Comment by NullVoxPopuli** [comment]
ya -- i think there may be a few issues for this bug

**Comment by kategengler** [comment]
Ok -- the Limber in the issue works, which is why I asked. @NullVoxPopuli Do you want to keep this one open or open one with what you know is broken on modern Ember?

**Comment by NullVoxPopuli** [comment]
I see, I suppose I am wrong or misremembering. Perhaps recent work _somewhere_ fixed this inadvertently. Before closing, I'll ask Copilot to find out which version of the code could have maybe fixed this 🙈

**Comment by NullVoxPopuli** [comment]
looks like we fixed here: 
- https://github.com/glimmerjs/glimmer-vm/pull/1565

so that would have been in a 5.9 beta
