### ISSUE TITLE
New ember projects don't run

### ISSUE THREAD

**Issue by Virock** [emberjs/ember.js#20805]
### 🐞 Describe the Bug
Running a new Ember project does not build properly.

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.
1. npm install -g ember-cli
2. ember new test --lang en
3. cd test
4. npm start

### 😕 Actual Behavior
A clear and concise description of what is happening.
Returns this error:
```
> test@0.0.0 start
> ember serve

Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-waiters]) in @ember/test-waiters/build-waiter.js

abc\test\@ember\test-waiters\build-waiter.js: Cannot read properties of undefined (reading 'params')TypeError: abc\test\@ember\test-waiters\build-waiter.js: Cannot read properties of undefined (reading 'params')
    at NodePath._getKey (abc\test\node_modules\@babel\traverse\lib\path\family.js:244:25)
    at NodePath.get (abc\test\node_modules\@babel\traverse\lib\path\family.js:237:20)
    at Object.Function (abc\test\node_modules\@babel\traverse\lib\scope\index.js:271:25)
    at _traverse (abc\test\node_modules\@babel\traverse\lib\scope\traverseForScope.js:37:17)
    at traverseForScope (abc\test\node_modules\@babel\traverse\lib\scope\traverseForScope.js:19:3)
    at Scope.crawl (abc\test\node_modules\@babel\traverse\lib\scope\index.js:658:35)
    at Scope.init (abc\test\node_modules\@babel\traverse\lib\scope\index.js:626:12)
    at NodePath.setScope (abc\test\node_modules\@babel\traverse\lib\path\context.js:141:53)
    at NodePath.setContext (abc\test\node_modules\@babel\traverse\lib\path\context.js:153:12)
    at NodePath.popContext (abc\test\node_modules\@babel\traverse\lib\path\context.js:205:10)
    at TraversalContext.visitQueue (abc\test\node_modules\@babel\traverse\lib\context.js:102:27)
    at TraversalContext.visitSingle (abc\test\node_modules\@babel\traverse\lib\context.js:66:19)
    at TraversalContext.visit (abc\test\node_modules\@babel\traverse\lib\context.js:113:19)
    at traverseNode (abc\test\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (abc\test\node_modules\@babel\traverse\lib\index.js:53:34)
    at transformFile (abc\test\node_modules\@babel\core\lib\transformation\index.js:80:31)
    at transformFile.next (<anonymous>)
    at run (abc\test\node_modules\@babel\core\lib\transformation\index.js:25:12)
    at run.next (<anonymous>)
    at transform (abc\test\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at evaluateSync (abc\test\node_modules\gensync\index.js:251:28)
    at sync (abc\test\node_modules\gensync\index.js:89:14)
    at stopHiding - secret - don't use this - v1 (abc\test\node_modules\@babel\core\lib\errors\rewrite-stack-trace.js:47:12)
    at Object.transform (abc\test\node_modules\@babel\core\lib\transform.js:36:80)
    at abc\test\node_modules\@ember\test-waiters\node_modules\broccoli-babel-transpiler\lib\worker.js:12:31
    at tryCatcher (abc\test\node_modules\@ember\test-waiters\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (abc\test\node_modules\@ember\test-waiters\node_modules\rsvp\dist\rsvp.js:498:33)
    at abc\test\node_modules\@ember\test-waiters\node_modules\rsvp\dist\rsvp.js:562:16
    at flush (abc\test\node_modules\@ember\test-waiters\node_modules\rsvp\dist\rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)


Stack Trace and Error Report: abc\AppData\Local\Temp/error.dump.9565fe7c1fd506e104cc323e62c43586.log
```

### 🤔 Expected Behavior
It should build successfully

### 🌍 Environment

- Ember: - 
- Ember-CLI: - 6.0.1
- Node.js/npm: - 20.12.2
- OS: - Win32 x64
- Browser: -

**Comment by NullVoxPopuli** [comment]
Looks like a babel bug!

**Comment by NullVoxPopuli** [comment]
See https://github.com/emberjs/ember.js/issues/20806#issuecomment-2517792244

**Comment by bertdeblock** [comment]
Can be closed now?

**Comment by acorncom** [comment]
Closing, thanks folks
