### ISSUE TITLE
`Cannot read properties of undefined (reading 'params')` from `@babel/traverse`

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#20806]
### 🐞 Describe the Bug

We noticed in tests that suddenly we can no longer build a simple Ember app. We get the build error:

https://github.com/getsentry/sentry-javascript/actions/runs/12159659201/job/33911464878#step:13:243

Or in a simple quick-start app:

```
ember-quickstart@0.0.0 build
> ember build --environment=production

Environment: production
⠸ building... [Babel: ember-source > applyPatches][BABEL] Note: The code generator has deoptimised the styling of /Users/francesco/git/temp-repos/ember-quickstart/ember/ember-template-compiler.js as it exceeds the max of 500KB.
⠋ building... [Babel: ember-source > applyPatches][BABEL] Note: The code generator has deoptimised the styling of /Users/francesco/git/temp-repos/ember-quickstart/ember/ember.js as it exceeds the max of 500KB.
cleaning up...
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-waiters]) in @ember/test-waiters/build-waiter.js

/Users/francesco/git/temp-repos/ember-quickstart/@ember/test-waiters/build-waiter.js: Cannot read properties of undefined (reading 'params')TypeError: /Users/francesco/git/temp-repos/ember-quickstart/@ember/test-waiters/build-waiter.js: Cannot read properties of undefined (reading 'params')
    at NodePath._getKey (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/path/family.js:244:25)
    at NodePath.get (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/path/family.js:237:20)
    at Object.Function (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/scope/index.js:271:25)
    at _traverse (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/scope/traverseForScope.js:37:17)
    at traverseForScope (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/scope/traverseForScope.js:19:3)
    at Scope.crawl (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/scope/index.js:658:35)
    at Scope.init (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/scope/index.js:626:12)
    at NodePath.setScope (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:141:53)
    at NodePath.setContext (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:153:12)
    at NodePath.popContext (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:205:10)
    at TraversalContext.visitQueue (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/context.js:102:27)
    at TraversalContext.visitSingle (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/context.js:66:19)
    at TraversalContext.visit (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/context.js:113:19)
    at traverseNode (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/traverse/lib/index.js:53:34)
    at transformFile (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/core/lib/transformation/index.js:80:31)
    at transformFile.next (<anonymous>)
    at run (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/core/lib/transformation/index.js:25:12)
    at run.next (<anonymous>)
    at transform (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/gensync/index.js:251:28)
    at sync (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.transform (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/@babel/core/lib/transform.js:36:80)
    at /Users/francesco/git/temp-repos/ember-quickstart/node_modules/ember-cli-test-loader/node_modules/broccoli-babel-transpiler/lib/worker.js:12:31
    at tryCatcher (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/ember-cli-test-loader/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/ember-cli-test-loader/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/francesco/git/temp-repos/ember-quickstart/node_modules/ember-cli-test-loader/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/francesco/git/temp-repos/ember-quickstart/node_modules/ember-cli-test-loader/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### 🔬 Minimal Reproduction

1. `npx ember-cli new ember-quickstart --lang en`
2. `cd ember-quickstart`
3. `npm run build`
4. --> See build error

You can also see it e.g. here, where we noticed it: https://github.com/getsentry/sentry-javascript/tree/develop/dev-packages/e2e-tests/test-applications/ember-classic

### 😕 Actual Behavior

Simple app fails build.

### 🤔 Expected Behavior

Build of simple app works.

### 🌍 Environment

Our test app is ember 4, but it is also in ember 6. Pretty sure this is related to some transitive dependency...

- Ember: 6.0.0
- Ember-CLI: 6.0.1
- Node.js/npm: 
- OS: 18.20.2
- Browser: -

**Comment by mydea** [comment]
Duplicate of https://github.com/emberjs/ember.js/issues/20805, I guess!

**Comment by mydea** [comment]
I am pretty sure this is because of `@babel/traverse` v7.26.3. If I force dependencies via:

```
 "resolutions": {
    "@babel/traverse": "7.25.9"
  },
```

It works!

**Comment by BryanCrotazGivEnergy** [comment]
in case it's useful, it fails with pnpm too

**Comment by yeinerfonseca** [comment]
For me using the embroider build system made it work. I generated the project like so:

`ember new super-rentals --lang en --embroider`

This is my version:

`ember-cli: 6.0.1`
`node: 22.12.0`
`os: linux x64`

**Comment by JLHwung** [comment]
This is an upstream issue and has been fixed in `@babel/traverse` 7.26.4.

**Comment by bertdeblock** [comment]
Can be closed now?

**Comment by acorncom** [comment]
Closing, thanks folks. Let know if we need to open this again
