### ISSUE TITLE
Error with transitionTo when running tests

### ISSUE THREAD

**Issue by jefflage** [emberjs/ember.js#5291]
i just upgraded from 1.5.0 to 1.6.1 and there has been a regression in one of my unit tests.

it is a test for a controller where i send it an action.  in the action handler, it calls `this.transitionTo`.  that call is generating the following stack.

please note, this is only happening when running tests, it does not happen when running the application.  it also is not causing any tests to fail.

```javascript
undefined is not a function TypeError: undefined is not a function
    at Object.__exports__.default.subclass.applyToHandlers (http://10.0.0.8:12379/lib/ember/ember.js:41471:25)
    at Object.__exports__.default.subclass.applyToState (http://10.0.0.8:12379/lib/ember/ember.js:41445:21)
    at Object.Router.transitionByIntent (http://10.0.0.8:12379/lib/ember/ember.js:40734:33)
    at doTransition (http://10.0.0.8:12379/lib/ember/ember.js:41339:21)
    at Object.Router.transitionTo (http://10.0.0.8:12379/lib/ember/ember.js:40887:16)
    at EmberObject.extend._doTransition (http://10.0.0.8:12379/lib/ember/ember.js:39372:53)
    at EmberObject.extend.transitionTo (http://10.0.0.8:12379/lib/ember/ember.js:39159:21)
    at ControllerMixin.reopen.transitionToRoute (http://10.0.0.8:12379/lib/ember/ember.js:34270:23)
    at App.DatastreamController.Ember.ObjectController.extend.actions.quicklinkChanged (http://10.0.0.8:12379/datastream/compiled/app.js:5637:18)
    at Mixin.create.send (http://10.0.0.8:12379/lib/ember/ember.js:15435:41) 
```

**Comment by dimitara** [comment]
Hi guys,

I am having the same issue. Prepared a quick example here: http://emberjs.jsbin.com/veleluhiku/1/

I was interested why transitionToRoute is undefined when executing from the test. I can work it around if I move the transitionToRoute call in the corresponding route but in general if I am allowed to go to a new route from the controller why does this breaks?

Cheers

**Comment by rwjblue** [comment]
Repro in JSBin does not seem to demonstrate the same issue.  Please open a new issue if still applicable.
